### ISSUE TITLE
3.4.1 bricks the CP

### ISSUE THREAD

**Issue by lukeyouell** [ethercreative/simplemap#125]
### Description

After updating from 3.4.0 to 3.4.1 the CP is inaccessible due to the following plugin error being thrown:

```
Setting unknown property: ether\simplemap\fields\MapField::height
```

Stack trace:

```
2019-03-20 15:26:38 [-][-][q7m7m51p9k0aff1tctiel6kuln][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: ether\simplemap\fields\MapField::height in /Users/luke/Sites/smudge/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /Users/luke/Sites/smudge/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('height', '400')
#1 /Users/luke/Sites/smudge/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(ether\simplemap\fields\MapField), Array)
#2 /Users/luke/Sites/smudge/vendor/craftcms/cms/src/helpers/Component.php(80): yii\base\BaseObject->__construct(Array)
#3 /Users/luke/Sites/smudge/vendor/craftcms/cms/src/services/Fields.php(548): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#4 /Users/luke/Sites/smudge/vendor/craftcms/cms/src/services/Fields.php(573): craft\services\Fields->createField(Array)
#5 /Users/luke/Sites/smudge/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1536): craft\services\Fields->getAllFields()
#6 /Users/luke/Sites/smudge/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1073): craft\elements\db\ElementQuery->customFields()
#7 /Users/luke/Sites/smudge/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#8 /Users/luke/Sites/smudge/vendor/yiisoft/yii2/db/Query.php(146): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
```

### Additional info

- Craft version: 3.1.19
- SimpleMap version: 3.4.1

**Comment by Tam** [comment]
Fixed in 3.4.2
