### ISSUE TITLE
Error on Saving Address

### ISSUE THREAD

**Issue by alexjcollins** [ethercreative/simplemap#126]
### Description
via [@avantlettre](https://twitter.com/avantlettre) on Twitter https://twitter.com/avantlettre/status/1108379190427041792

### Error
`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'elementId' cannot be null`

The SQL being executed was: 
```
INSERT INTO `simplemaps` (`elementId`, `ownerId`, `ownerSiteId`, `fieldId`, `lat`, `lng`, `zoom`, `address`, `parts`, `dateCreated`, `uid`, `dateUpdated`) VALUES (NULL, ····· )
```

**Comment by alexjcollins** [comment]
@ogilv Would you be able to paste a Stack Trace?

**Comment by ogilv** [comment]
```
Twig_Error_Runtime: Neither the property "street_address" nor one of the methods "street_address()", "getstreet_address()"/"isstreet_address()"/"hasstreet_address()" or "__call()" exist and have public access in class "ether\simplemap\models\Parts". in /home/httpd/vhosts/•••.ch/subdomains/•••/templates/rubriken/_mitglieder.html:24
Stack trace:
#0 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(ether\simplemap\models\Parts), 'street_address', Array, 'any', false, false)
#1 /home/httpd/vhosts/•••.ch/subdomains/•••/storage/runtime/compiled_templates/cb/cb9846d601c6c7ba7823a48791de4a93bab6df50d9ab6c7fef65b3ee7808c5c5.php(69): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(ether\simplemap\models\Parts), 'street_address', Array)
#2 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_fbac1693d6e08acf0760ad58b8b264c092d14306deaddf91ac6b2e9089a1c59e->doDisplay(Array, Array)
#3 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#4 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#5 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#6 /home/httpd/vhosts/•••.ch/subdomains/•••/storage/runtime/compiled_templates/57/570996ccc292c9aac87c71cfd840872d1e42a8858e82e756c86c1b22ea388b85.php(36): craft\web\twig\Template->display(Array)
#7 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_1f365a2e56156bd766bb889ad882627cd33de92d0d267d69d7558fe2bfe876a6->block_content(Array, Array)
#8 /home/httpd/vhosts/•••.ch/subdomains/•••/storage/runtime/compiled_templates/8f/8f1e245a6d9d2eefefad3d877ac9dce09bd27883fbd3de364bb4a6c1a80fa4af.php(143): Twig_Template->displayBlock('content', Array, Array)
#9 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_82da90109b44646dfbf4a27cac2aa409cce576d5d1d7f7920bae439922b34e51->doDisplay(Array, Array)
#10 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#11 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#12 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#13 /home/httpd/vhosts/•••.ch/subdomains/•••/storage/runtime/compiled_templates/57/570996ccc292c9aac87c71cfd840872d1e42a8858e82e756c86c1b22ea388b85.php(28): craft\web\twig\Template->display(Array, Array)
#14 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_1f365a2e56156bd766bb889ad882627cd33de92d0d267d69d7558fe2bfe876a6->doDisplay(Array, Array)
#15 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#16 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#17 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#18 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->display(Array)
#19 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#20 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/View.php(337): Twig_Environment->render('rubriken/_entry', Array)
#21 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/View.php(384): craft\web\View->renderTemplate('rubriken/_entry', Array)
#22 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('rubriken/_entry', Array)
#23 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('rubriken/_entry', Array)
#24 [internal function]: craft\controllers\TemplatesController->actionRender('rubriken/_entry', Array)
#25 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#26 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#27 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('render', Array)
#28 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#29 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('templates/rende...', Array)
#30 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#31 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#32 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#33 /home/httpd/vhosts/•••.ch/subdomains/•••/web/index.php(21): yii\base\Application->run()
#34 {main}
```

**Comment by Tam** [comment]
@ogilv Are you using Google as your geo-service, or something else?

**Comment by ogilv** [comment]
@Tam Yes, I do use the Google API. But I just switched to the opensource defaults, and got the same error again.

**Comment by ogilv** [comment]
Two factors that might be of importance:
- There was an error on update that I could not resolve via control panel, but after deleting the single test entry in the `simplemaps` table, I could proceed and finish the update.
- My custom field belongs to a user, not a regular entry.

**Comment by Tam** [comment]
Could you share the template code where you're outputting the map in `rubriken/_entry`?

**Comment by ogilv** [comment]
Oh, I just noticed I posted the frontend stacktrace above, although the error is seen first in the control panel, after the location has been found and I try to save the entry:

```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'elementId' cannot be null in /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/Command.php:1290
Stack trace:
#0 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute()
#1 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO `si...')
#2 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/Schema.php(433): yii\db\Command->execute()
#3 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/ActiveRecord.php(555): yii\db\Schema->insert('{{%simplemaps}}', Array)
#4 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/ActiveRecord.php(521): yii\db\ActiveRecord->insertInternal(NULL)
#5 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL)
#6 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/ether/simplemap/src/services/MapService.php(94): yii\db\BaseActiveRecord->save()
#7 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/ether/simplemap/src/fields/MapField.php(389): ether\simplemap\services\MapService->saveField(Object(ether\simplemap\fields\MapField), Object(craft\elements\User))
#8 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/base/Element.php(1883): ether\simplemap\fields\MapField->afterElementSave(Object(craft\elements\User), false)
#9 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/elements/User.php(1322): craft\base\Element->afterSave(false)
#10 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/services/Elements.php(515): craft\elements\User->afterSave(false)
#11 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/controllers/UsersController.php(1091): craft\services\Elements->saveElement(Object(craft\elements\User), false)
#12 [internal function]: craft\controllers\UsersController->actionSaveUser()
#13 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('save-user', Array)
#16 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-user', Array)
#17 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('users/save-user', Array)
#18 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('users/save-user', Array)
#19 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /home/httpd/vhosts/•••.ch/subdomains/•••/web/index.php(21): yii\base\Application->run()
#22 {main}

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'elementId' cannot be null
The SQL being executed was: INSERT INTO `simplemaps` (`elementId`, `ownerId`, `ownerSiteId`, `fieldId`, `lat`, `lng`, `zoom`, `address`, `parts`, `dateCreated`, `uid`, `dateUpdated`) VALUES (NULL, 70, 1, 27, '47.3765', '8.5235245', 12, 'Anwandstrasse, Langstrasse, Aussersihl, Zürich, Bezirk Zürich, Zürich, 8004, Schweiz', '{\"number\":\"\",\"address\":\"Anwandstrasse, Aussersihl\",\"city\":\"Zürich\",\"postcode\":\"8004\",\"county\":\"Bezirk Zürich\",\"state\":\"Zürich\",\"country\":\"Schweiz\"}', '2019-03-20 15:26:58', '996aced0-8fbf-4988-a4a0-b67c0c6e48f6', '2019-03-20 15:26:58') in /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `si...')
#1 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO `si...')
#2 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/Schema.php(433): yii\db\Command->execute()
#3 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/ActiveRecord.php(555): yii\db\Schema->insert('{{%simplemaps}}', Array)
#4 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/ActiveRecord.php(521): yii\db\ActiveRecord->insertInternal(NULL)
#5 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL)
#6 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/ether/simplemap/src/services/MapService.php(94): yii\db\BaseActiveRecord->save()
#7 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/ether/simplemap/src/fields/MapField.php(389): ether\simplemap\services\MapService->saveField(Object(ether\simplemap\fields\MapField), Object(craft\elements\User))
#8 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/base/Element.php(1883): ether\simplemap\fields\MapField->afterElementSave(Object(craft\elements\User), false)
#9 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/elements/User.php(1322): craft\base\Element->afterSave(false)
#10 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/services/Elements.php(515): craft\elements\User->afterSave(false)
#11 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/controllers/UsersController.php(1091): craft\services\Elements->saveElement(Object(craft\elements\User), false)
#12 [internal function]: craft\controllers\UsersController->actionSaveUser()
#13 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('save-user', Array)
#16 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-user', Array)
#17 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('users/save-user', Array)
#18 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('users/save-user', Array)
#19 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#20 /home/httpd/vhosts/•••.ch/subdomains/•••/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /home/httpd/vhosts/•••.ch/subdomains/•••/web/index.php(21): yii\base\Application->run()
#22 {main}
Additional Information:
Array
(
    [0] => 23000
    [1] => 1048
    [2] => Column 'elementId' cannot be null
)


```

**Comment by ogilv** [comment]
The template code is as follows:

```
{% for mitglied in craft.users.group('mitglieder').status('pending').all() %}
	<p>{{ mitglied.ort.parts.street_address }}
{% endfor %}
```

The `simplemaps` table is empty, since I have not been able to save any location field data to it (but before the update, this did not produce an error on the frontend).
