### ISSUE TITLE
Compatibility issue w/ cp-field-inspect

### ISSUE THREAD

**Issue by Tam** [ethercreative/simplemap#127]
Trying to get property 'map' of non-object when `cp-field-inspect` plugin is installed. (MapField.php:353)

**Comment by chasegiunta** [comment]
```
yii\base\ErrorException: Trying to get property of non-object in /Users/chasegiunta/Sites/thecentercounseling/vendor/ether/simplemap/src/fields/MapField.php:353
Stack trace:
#0 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/Users/chasegiu...', 353)
#1 /Users/chasegiunta/Sites/thecentercounseling/vendor/ether/simplemap/src/fields/MapField.php(353): craft\web\ErrorHandler->handleError(8, 'Trying to get p...', '/Users/chasegiu...', 353, Array)
#2 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1651): ether\simplemap\fields\MapField->modifyElementsQuery(Object(craft\elements\db\UserQuery), NULL)
#3 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1074): craft\elements\db\ElementQuery->_joinContentTable('craft\\elements\\...')
#4 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#5 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/db/Query.php(146): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#6 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Query->createCommand(Object(craft\db\Connection))
#7 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#8 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1215): craft\db\Query->one(NULL)
#9 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/elements/User.php(366): craft\elements\db\ElementQuery->one()
#10 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/web/User.php(690): craft\elements\User::findIdentity('1')
#11 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/web/User.php(488): yii\web\User->renewAuthStatus()
#12 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/web/User.php(192): craft\web\User->renewAuthStatus()
#13 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/web/User.php(231): yii\web\User->getIdentity()
#14 /Users/chasegiunta/Sites/thecentercounseling/vendor/mmikkel/cp-field-inspect/src/CpFieldInspect.php(76): craft\web\User->getIsAdmin()
#15 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/base/BaseObject.php(109): mmikkel\cpfieldinspect\CpFieldInspect->init()
#16 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#17 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/base/Plugin.php(127): yii\base\Module->__construct('cp-field-inspec...', Object(craft\web\Application), Array)
#18 [internal function]: craft\base\Plugin->__construct('cp-field-inspec...', Object(craft\web\Application), Array)
#19 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#20 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('mmikkel\\cpfield...', Array, Array)
#21 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('mmikkel\\cpfield...', Array, Array)
#22 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#23 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins->createPlugin('cp-field-inspec...', Array)
#24 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/base/ApplicationTrait.php(1225): craft\services\Plugins->loadPlugins()
#25 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application->_postInit()
#26 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#27 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#28 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application->__construct(Array)
#29 [internal function]: craft\web\Application->__construct(Array)
#30 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#31 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#32 /Users/chasegiunta/Sites/thecentercounseling/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#33 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/bootstrap/bootstrap.php(255): yii\BaseYii::createObject(Array)
#34 /Users/chasegiunta/Sites/thecentercounseling/vendor/craftcms/cms/bootstrap/web.php(42): require('/Users/chasegiu...')
#35 /Users/chasegiunta/Sites/thecentercounseling/web/index.php(20): require('/Users/chasegiu...')
#36 /Users/chasegiunta/.composer/vendor/laravel/valet/server.php(158): require('/Users/chasegiu...')
#37 {main}
```
