### ISSUE TITLE
Migration Faliure

### ISSUE THREAD

**Issue by alexjcollins** [ethercreative/simplemap#130]
### Description
 > Via HelpScout. Un-redacted version in there

Running latest update.
-----------------------------------------------------------
```
Integrity constraint violation: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'elementId' cannot be null
The SQL being executed was: INSERT INTO `craft_simplemaps` (`elementId`, `ownerId`, `ownerSiteId`, `fieldId`, `lat`, `lng`, `zoom`, `address`, `parts`, `dateCreated`, `uid`, `dateUpdated`) VALUES (NULL, 4816, 1, 10, '33.937722500', '-84.244767900', NULL, 'Topiary Courtyard, Jones Mill Road, Norcross, GA, USA', '{\"number\":\"\",\"address\":\"\",\"city\":\"\",\"postcode\":\"\",\"county\":\"\",\"state\":\"\",\"country\":\"\"}', '2019-03-20 22:29:14', 'a4a005d2-d01c-4e74-b87a-cc9592511c6b', '2019-03-20 22:29:14')
```
Migration: ether\simplemap\migrations\m190226_143809_craft3_upgrade

Output:

```
> Start map data upgrade
> drop table {{%simplemaps}} ... done (time: 0.003s)
> create table {{%simplemaps}} ... done (time: 0.016s)
> create unique index craft_simplemaps_ownerId_ownerSiteId_fieldId_elementId_unq_idx on {{%simplemaps}} (ownerId,ownerSiteId,fieldId,elementId) ... done (time: 0.015s)
> create index craft_simplemaps_lat_idx on {{%simplemaps}} (lat) ... done (time: 0.011s)
> create index craft_simplemaps_lng_idx on {{%simplemaps}} (lng) ... done (time: 0.014s)
> add foreign key craft_simplemaps_elementId_fk: {{%simplemaps}} (elementId) references {{%elements}} (id) ... done (time: 0.023s)
> add foreign key craft_simplemaps_ownerId_fk: {{%simplemaps}} (ownerId) references {{%elements}} (id) ... done (time: 0.017s)
> add foreign key craft_simplemaps_ownerSiteId_fk: {{%simplemaps}} (ownerSiteId) references {{%sites}} (id) ... done (time: 0.039s)
> add foreign key craft_simplemaps_fieldId_fk: {{%simplemaps}} (fieldId) references {{%fields}} (id) ... done (time: 0.037s)

> ***Bunch of successful upgrades***

Exception: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'elementId' cannot be null
The SQL being executed was: INSERT INTO `craft_simplemaps` (`elementId`, `ownerId`, `ownerSiteId`, `fieldId`, `lat`, `lng`, `zoom`, `address`, `parts`, `dateCreated`, `uid`, `dateUpdated`) VALUES (NULL, 4816, 1, 10, '33.937722500', '-84.244767900', NULL, 'Topiary Courtyard, Jones Mill Road, Norcross, GA, USA', '{\"number\":\"\",\"address\":\"\",\"city\":\"\",\"postcode\":\"\",\"county\":\"\",\"state\":\"\",\"country\":\"\"}', '2019-03-20 22:29:14', 'a4a005d2-d01c-4e74-b87a-cc9592511c6b', '2019-03-20 22:29:14') (/Users/Chad/Sites/american-conifer-society/site/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/Chad/Sites/american-conifer-society/site/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `cr...')
#1 /Users/Chad/Sites/american-conifer-society/site/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO `cr...')
#2 /Users/Chad/Sites/american-conifer-society/site/vendor/yiisoft/yii2/db/Schema.php(433): yii\db\Command->execute()
#3 /Users/Chad/Sites/american-conifer-society/site/vendor/yiisoft/yii2/db/ActiveRecord.php(555): yii\db\Schema->insert('{{%simplemaps}}', Array)
#4 /Users/Chad/Sites/american-conifer-society/site/vendor/yiisoft/yii2/db/ActiveRecord.php(521): yii\db\ActiveRecord->insertInternal(NULL)
#5 /Users/Chad/Sites/american-conifer-society/site/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL)
#6 /Users/Chad/Sites/american-conifer-society/site/vendor/ether/simplemap/src/migrations/m190226_143809_craft3_upgrade.php(216): yii\db\BaseActiveRecord->save()
#7 /Users/Chad/Sites/american-conifer-society/site/vendor/ether/simplemap/src/migrations/m190226_143809_craft3_upgrade.php(50): ether\simplemap\migrations\m190226_143809_craft3_upgrade->_upgrade3()
#8 /Users/Chad/Sites/american-conifer-society/site/vendor/craftcms/cms/src/db/Migration.php(56): ether\simplemap\migrations\m190226_143809_craft3_upgrade->safeUp()
#9 /Users/Chad/Sites/american-conifer-society/site/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#10 /Users/Chad/Sites/american-conifer-society/site/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(ether\simplemap\migrations\m190226_143809_craft3_upgrade))
#11 /Users/Chad/Sites/american-conifer-society/site/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#12 /Users/Chad/Sites/american-conifer-society/site/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#13 /Users/Chad/Sites/american-conifer-society/site/vendor/craftcms/cms/src/controllers/UpdaterController.php(209): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#14 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#15 /Users/Chad/Sites/american-conifer-society/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /Users/Chad/Sites/american-conifer-society/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /Users/Chad/Sites/american-conifer-society/site/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#18 /Users/Chad/Sites/american-conifer-society/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#19 /Users/Chad/Sites/american-conifer-society/site/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#20 /Users/Chad/Sites/american-conifer-society/site/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#21 /Users/Chad/Sites/american-conifer-society/site/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#22 /Users/Chad/Sites/american-conifer-society/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /Users/Chad/Sites/american-conifer-society/site/public_html/index.php(21): yii\base\Application->run()
#24 {main}
```

**Comment by alexjcollins** [comment]
@chadcrowell I hope you don't mind, but I've created an issue for your support email so it's easier for us to manage. Let me know if you require anything other than the addresses redacted from here. We'll be in touch if we need any extra info.

**Comment by mhulet** [comment]
I have the same issue upgrading from 3.3.5 to 3.4.3.

```
Integrity constraint violation: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'elementId' cannot be null
The SQL being executed was: INSERT INTO craft_simplemaps (elementId, ownerId, ownerSiteId, fieldId, lat, lng, zoom, address, parts, dateCreated, uid, dateUpdated) VALUES (NULL, 47, 2, 55, '50.689245100', '4.410611100', NULL, 'Chaussée de Charleroi 579, 1410 Waterloo', '{\"number\":\"\",\"address\":\"\",\"city\":\"\",\"postcode\":\"\",\"county\":\"\",\"state\":\"\",\"country\":\"Belgique\"}', '2019-03-21 17:10:48', '98d7ff5f-1363-400f-89a7-ef5ba423a50b', '2019-03-21 17:10:48')

Migration: ether\simplemap\migrations\m190226_143809_craft3_upgrade

Output:

> Start map data upgrade
> drop table {{%simplemaps}} ... done (time: 0.018s)
> create table {{%simplemaps}} ... done (time: 0.017s)
> create unique index craft_simplemaps_ownerId_ownerSiteId_fieldId_elementId_unq_idx on {{%simplemaps}} (ownerId,ownerSiteId,fieldId,elementId) ... done (time: 0.010s)
> create index craft_simplemaps_lat_idx on {{%simplemaps}} (lat) ... done (time: 0.010s)
> create index craft_simplemaps_lng_idx on {{%simplemaps}} (lng) ... done (time: 0.010s)
> add foreign key craft_simplemaps_elementId_fk: {{%simplemaps}} (elementId) references {{%elements}} (id) ... done (time: 0.039s)
> add foreign key craft_simplemaps_ownerId_fk: {{%simplemaps}} (ownerId) references {{%elements}} (id) ... done (time: 0.032s)
> add foreign key craft_simplemaps_ownerSiteId_fk: {{%simplemaps}} (ownerSiteId) references {{%sites}} (id) ... done (time: 0.035s)
> add foreign key craft_simplemaps_fieldId_fk: {{%simplemaps}} (fieldId) references {{%fields}} (id) ... done (time: 0.035s)
> Upgrade map value Novabirra
> Upgrade map value Novabirra
> Upgrade map value Novabirra
> Upgrade map value rue du Fond du Maréchal 25, Suarlée, Belgium
> Upgrade map value rue du Fond du Maréchal 25, Suarlée, Belgium
> Upgrade map value Rue des Wallons 8, Ottignies-Louvain-la-Neuve, Belgium
> Upgrade map value Rue des Wallons 8, Ottignies-Louvain-la-Neuve, Belgium
> Upgrade map value Rue des Ormes 11, 1370 Jodoigne, Belgium
> Upgrade map value Rue des Ormes 11, 1370 Jodoigne, Belgium
> Upgrade map value Chaussée de Charleroi 579, 1410 Waterloo
Exception: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'elementId' cannot be null
The SQL being executed was: INSERT INTO craft_simplemaps (elementId, ownerId, ownerSiteId, fieldId, lat, lng, zoom, address, parts, dateCreated, uid, dateUpdated) VALUES (NULL, 47, 2, 55, '50.689245100', '4.410611100', NULL, 'Chaussée de Charleroi 579, 1410 Waterloo', '{\"number\":\"\",\"address\":\"\",\"city\":\"\",\"postcode\":\"\",\"county\":\"\",\"state\":\"\",\"country\":\"Belgique\"}', '2019-03-21 17:10:48', '98d7ff5f-1363-400f-89a7-ef5ba423a50b', '2019-03-21 17:10:48') (/app/craft/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /app/craft/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO cr...')
#1 /app/craft/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO cr...')
#2 /app/craft/vendor/yiisoft/yii2/db/Schema.php(433): yii\db\Command->execute()
#3 /app/craft/vendor/yiisoft/yii2/db/ActiveRecord.php(555): yii\db\Schema->insert('{{%simplemaps}}', Array)
#4 /app/craft/vendor/yiisoft/yii2/db/ActiveRecord.php(521): yii\db\ActiveRecord->insertInternal(NULL)
#5 /app/craft/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL)
#6 /app/craft/vendor/ether/simplemap/src/migrations/m190226_143809_craft3_upgrade.php(216): yii\db\BaseActiveRecord->save()
#7 /app/craft/vendor/ether/simplemap/src/migrations/m190226_143809_craft3_upgrade.php(50): ether\simplemap\migrations\m190226_143809_craft3_upgrade->_upgrade3()
#8 /app/craft/vendor/craftcms/cms/src/db/Migration.php(56): ether\simplemap\migrations\m190226_143809_craft3_upgrade->safeUp()
#9 /app/craft/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#10 /app/craft/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(ether\simplemap\migrations\m190226_143809_craft3_upgrade))
#11 /app/craft/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#12 /app/craft/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#13 /app/craft/vendor/craftcms/cms/src/controllers/UpdaterController.php(209): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#14 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#15 /app/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /app/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /app/craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#18 /app/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#19 /app/craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#20 /app/craft/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#21 /app/craft/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#22 /app/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /app/site/index.php(23): yii\base\Application->run()
#24 {main}
```

**Comment by Tam** [comment]
@mhulet Would you be able to share the contents of your `simplemaps` table?

**Comment by mhulet** [comment]
@Tam Sure, here are the current records on my local instance, where the upgrade process is currently failing.

```
INSERT INTO `craft_simplemaps` (`id`, `ownerId`, `ownerSiteId`, `fieldId`, `lat`, `lng`, `zoom`, `address`, `parts`, `dateCreated`, `dateUpdated`, `uid`)
VALUES
	(1, 5, 2, 54, 50.687732900, 4.383497800, 15, 'Novabirra', '[]', '2018-10-05 04:28:45', '2019-03-04 10:58:18', '98aeb87e-3c81-43f9-99c8-b267109a793e'),
	(2, 5, 1, 54, 50.687732900, 4.383497800, 15, 'Novabirra', '[]', '2018-10-05 04:28:45', '2019-03-04 10:58:18', '4f48792c-8d15-4346-934d-c8710ef02304'),
	(3, 5, 3, 54, 50.687732900, 4.383497800, 15, 'Novabirra', '[]', '2018-10-05 04:28:45', '2019-03-04 10:58:18', '1767636e-0c92-45be-951c-89a1b8438138'),
	(4, 43, 2, 55, 50.487548000, 4.793246000, 15, 'rue du Fond du Maréchal 25, Suarlée, Belgium', '{\"street_number\":\"25\",\"street_number_short\":\"25\",\"route\":\"Rue du Fond du Maréchal\",\"route_short\":\"Rue du Fond du Maréchal\",\"locality\":\"Suarlée\",\"locality_short\":\"Suarlée\",\"administrative_area_level_2\":\"Namur\",\"administrative_area_level_2_short\":\"NA\",\"administrative_area_level_1\":\"Wallonie\",\"administrative_area_level_1_short\":\"Wallonie\",\"country\":\"Belgique\",\"country_short\":\"BE\",\"postal_code\":\"5020\",\"postal_code_short\":\"5020\"}', '2018-10-05 04:52:02', '2018-10-09 04:25:02', '0736b186-b092-4712-a53a-0ca340815e90'),
	(5, 43, 1, 55, 50.487548000, 4.793246000, 15, 'rue du Fond du Maréchal 25, Suarlée, Belgium', '{\"street_number\":\"25\",\"street_number_short\":\"25\",\"route\":\"Rue du Fond du Maréchal\",\"route_short\":\"Rue du Fond du Maréchal\",\"locality\":\"Suarlée\",\"locality_short\":\"Suarlée\",\"administrative_area_level_2\":\"Namur\",\"administrative_area_level_2_short\":\"NA\",\"administrative_area_level_1\":\"Wallonie\",\"administrative_area_level_1_short\":\"Wallonie\",\"country\":\"Belgium\",\"country_short\":\"BE\",\"postal_code\":\"5020\",\"postal_code_short\":\"5020\"}', '2018-10-05 04:52:02', '2018-10-09 04:25:02', '6aae8952-4bf8-40cf-81ef-21ef5bfea06b'),
	(6, 45, 2, 55, 50.669554100, 4.615661400, 15, 'Rue des Wallons 8, Ottignies-Louvain-la-Neuve, Belgium', '{\"premise\":\"Halles Universitaires (RECT-ADMG)\",\"premise_short\":\"Halles Universitaires (RECT-ADMG)\",\"street_number\":\"6\",\"street_number_short\":\"6\",\"route\":\"Rue des Wallons\",\"route_short\":\"Rue des Wallons\",\"locality\":\"Ottignies-Louvain-la-Neuve\",\"locality_short\":\"Ottignies-Louvain-la-Neuve\",\"administrative_area_level_2\":\"Brabant Wallon\",\"administrative_area_level_2_short\":\"BW\",\"administrative_area_level_1\":\"Wallonie\",\"administrative_area_level_1_short\":\"Wallonie\",\"country\":\"Belgique\",\"country_short\":\"BE\",\"postal_code\":\"1348\",\"postal_code_short\":\"1348\"}', '2018-10-09 03:55:26', '2018-10-09 04:24:55', '5fcaad9d-0431-4367-9ccd-c861bd08d1f6'),
	(7, 45, 1, 55, 50.669554100, 4.615661400, 15, 'Rue des Wallons 8, Ottignies-Louvain-la-Neuve, Belgium', '{\"premise\":\"Halles Universitaires (RECT-ADMG)\",\"premise_short\":\"Halles Universitaires (RECT-ADMG)\",\"street_number\":\"6\",\"street_number_short\":\"6\",\"route\":\"Rue des Wallons\",\"route_short\":\"Rue des Wallons\",\"locality\":\"Ottignies-Louvain-la-Neuve\",\"locality_short\":\"Ottignies-Louvain-la-Neuve\",\"administrative_area_level_2\":\"Brabant Wallon\",\"administrative_area_level_2_short\":\"BW\",\"administrative_area_level_1\":\"Wallonie\",\"administrative_area_level_1_short\":\"Wallonie\",\"country\":\"Belgium\",\"country_short\":\"BE\",\"postal_code\":\"1348\",\"postal_code_short\":\"1348\"}', '2018-10-09 03:55:26', '2018-10-09 04:24:55', 'fa5df93e-f909-4710-a775-f7bc985e35bd'),
	(8, 46, 2, 55, 50.780836945, 4.784729940, 19, 'Rue des Ormes 11, 1370 Jodoigne, Belgium', '{\"street_number\":\"11\",\"street_number_short\":\"11\",\"route\":\"Rue des Ormes\",\"route_short\":\"Rue des Ormes\",\"locality\":\"Jodoigne\",\"locality_short\":\"Jodoigne\",\"administrative_area_level_2\":\"Brabant Wallon\",\"administrative_area_level_2_short\":\"BW\",\"administrative_area_level_1\":\"Wallonie\",\"administrative_area_level_1_short\":\"Wallonie\",\"country\":\"Belgique\",\"country_short\":\"BE\",\"postal_code\":\"1370\",\"postal_code_short\":\"1370\"}', '2018-10-09 03:57:01', '2018-10-09 04:24:47', '4d296217-ba6d-4407-b44e-15c7901dae66'),
	(9, 46, 1, 55, 50.780836945, 4.784729940, 19, 'Rue des Ormes 11, 1370 Jodoigne, Belgium', '{\"street_number\":\"11\",\"street_number_short\":\"11\",\"route\":\"Rue des Ormes\",\"route_short\":\"Rue des Ormes\",\"locality\":\"Jodoigne\",\"locality_short\":\"Jodoigne\",\"administrative_area_level_2\":\"Brabant Wallon\",\"administrative_area_level_2_short\":\"BW\",\"administrative_area_level_1\":\"Wallonie\",\"administrative_area_level_1_short\":\"Wallonie\",\"country\":\"Belgium\",\"country_short\":\"BE\",\"postal_code\":\"1370\",\"postal_code_short\":\"1370\"}', '2018-10-09 03:57:01', '2018-10-09 04:24:48', 'cd1a226b-0762-4334-ae6a-11c9f73be7e5'),
	(10, 47, 2, 55, 50.689245100, 4.410611100, NULL, 'Chaussée de Charleroi 579, 1410 Waterloo', '{\"street_number\":\"579\",\"street_number_short\":\"579\",\"route\":\"Chaussée de Charleroi\",\"route_short\":\"Chaussée de Charleroi\",\"locality\":\"Waterloo\",\"locality_short\":\"Waterloo\",\"administrative_area_level_2\":\"Brabant Wallon\",\"administrative_area_level_2_short\":\"BW\",\"administrative_area_level_1\":\"Wallonie\",\"administrative_area_level_1_short\":\"Wallonie\",\"country\":\"Belgique\",\"country_short\":\"BE\",\"postal_code\":\"1410\",\"postal_code_short\":\"1410\"}', '2018-10-09 04:37:49', '2018-10-09 04:37:49', 'f363fd58-ed4c-4265-a0f2-2426d7ffff6b'),
	(11, 47, 1, 55, 50.689245100, 4.410611100, NULL, 'Chaussée de Charleroi 579, 1410 Waterloo', '{\"street_number\":\"579\",\"street_number_short\":\"579\",\"route\":\"Chaussée de Charleroi\",\"route_short\":\"Chaussée de Charleroi\",\"locality\":\"Waterloo\",\"locality_short\":\"Waterloo\",\"administrative_area_level_2\":\"Brabant Wallon\",\"administrative_area_level_2_short\":\"BW\",\"administrative_area_level_1\":\"Wallonie\",\"administrative_area_level_1_short\":\"Wallonie\",\"country\":\"Belgium\",\"country_short\":\"BE\",\"postal_code\":\"1410\",\"postal_code_short\":\"1410\"}', '2018-10-09 04:37:49', '2018-10-09 04:37:49', 'b6defd23-993b-43f6-b44d-ddb2c70bed58'),
	(12, 48, 2, 55, 48.872226941, 2.300161780, 15, '106 Av. des Champs-Élysées, 75008 Paris, France', '{\"street_number\":\"106\",\"street_number_short\":\"106\",\"route\":\"Avenue des Champs-Élysées\",\"route_short\":\"Av. des Champs-Élysées\",\"locality\":\"Paris\",\"locality_short\":\"Paris\",\"administrative_area_level_2\":\"Paris\",\"administrative_area_level_2_short\":\"Paris\",\"administrative_area_level_1\":\"Île-de-France\",\"administrative_area_level_1_short\":\"Île-de-France\",\"country\":\"France\",\"country_short\":\"FR\",\"postal_code\":\"75008\",\"postal_code_short\":\"75008\"}', '2018-10-09 04:38:34', '2018-10-09 04:38:34', '5eca9ad2-0ae1-4ee5-9f4c-bd864b68cd40'),
	(13, 48, 1, 55, 48.872226941, 2.300161780, 15, '106 Av. des Champs-Élysées, 75008 Paris, France', '{\"street_number\":\"106\",\"street_number_short\":\"106\",\"route\":\"Avenue des Champs-Élysées\",\"route_short\":\"Av. des Champs-Élysées\",\"locality\":\"Paris\",\"locality_short\":\"Paris\",\"administrative_area_level_2\":\"Paris\",\"administrative_area_level_2_short\":\"Paris\",\"administrative_area_level_1\":\"Île-de-France\",\"administrative_area_level_1_short\":\"Île-de-France\",\"country\":\"France\",\"country_short\":\"FR\",\"postal_code\":\"75008\",\"postal_code_short\":\"75008\"}', '2018-10-09 04:38:34', '2018-10-09 04:38:34', 'b534f37a-7d80-428f-9f8f-53c3a6c81904'),
	(14, 53, 2, 55, 50.489596000, 5.095612000, 15, 'Itinérances Gourmandes, Place des Tilleuls, Andenne, Belgium', '{\"street_number\":\"41\",\"street_number_short\":\"41\",\"route\":\"Place des Tilleuls\",\"route_short\":\"Place des Tilleuls\",\"locality\":\"Andenne\",\"locality_short\":\"Andenne\",\"administrative_area_level_2\":\"Namur\",\"administrative_area_level_2_short\":\"NA\",\"administrative_area_level_1\":\"Wallonie\",\"administrative_area_level_1_short\":\"Wallonie\",\"country\":\"Belgique\",\"country_short\":\"BE\",\"postal_code\":\"5300\",\"postal_code_short\":\"5300\"}', '2018-10-09 04:55:21', '2018-10-09 04:55:21', '0d2a2760-580d-4a5d-a833-38edf4331b37'),
	(15, 53, 1, 55, 50.489596000, 5.095612000, 15, 'Itinérances Gourmandes, Place des Tilleuls, Andenne, Belgium', '{\"street_number\":\"41\",\"street_number_short\":\"41\",\"route\":\"Place des Tilleuls\",\"route_short\":\"Place des Tilleuls\",\"locality\":\"Andenne\",\"locality_short\":\"Andenne\",\"administrative_area_level_2\":\"Namur\",\"administrative_area_level_2_short\":\"NA\",\"administrative_area_level_1\":\"Wallonie\",\"administrative_area_level_1_short\":\"Wallonie\",\"country\":\"Belgium\",\"country_short\":\"BE\",\"postal_code\":\"5300\",\"postal_code_short\":\"5300\"}', '2018-10-09 04:55:21', '2018-10-09 04:55:21', '8aff2f0f-c2fb-47fe-b0d1-ee386e337701'),
	(16, 54, 2, 55, 50.467668500, 4.871887700, 15, 'Rue Général Michel 31, 5000 Namur, Belgium', '{\"street_number\":\"33\",\"street_number_short\":\"33\",\"route\":\"Rue Général Michel\",\"route_short\":\"Rue Général Michel\",\"locality\":\"Namur\",\"locality_short\":\"Namur\",\"administrative_area_level_2\":\"Namur\",\"administrative_area_level_2_short\":\"NA\",\"administrative_area_level_1\":\"Wallonie\",\"administrative_area_level_1_short\":\"Wallonie\",\"country\":\"Belgique\",\"country_short\":\"BE\",\"postal_code\":\"5000\",\"postal_code_short\":\"5000\"}', '2018-10-09 04:55:55', '2018-10-09 04:55:55', 'fb8ef516-d144-4d3d-82e3-f282b7e379b0'),
	(17, 54, 1, 55, 50.467668500, 4.871887700, 15, 'Rue Général Michel 31, 5000 Namur, Belgium', '{\"street_number\":\"31\",\"street_number_short\":\"31\",\"route\":\"Rue Général Michel\",\"route_short\":\"Rue Général Michel\",\"locality\":\"Namur\",\"locality_short\":\"Namur\",\"administrative_area_level_2\":\"Namur\",\"administrative_area_level_2_short\":\"NA\",\"administrative_area_level_1\":\"Wallonie\",\"administrative_area_level_1_short\":\"Wallonie\",\"country\":\"Belgium\",\"country_short\":\"BE\",\"postal_code\":\"5000\",\"postal_code_short\":\"5000\"}', '2018-10-09 04:55:55', '2018-10-09 04:55:55', 'ddb44071-f17d-4aa2-b1f5-cc676764051d');

```

**Comment by Tam** [comment]
@mhulet Just released 3.4.4, can you try upgrading directly to it and let me know if it fixes your issues.

**Comment by chromadesign** [comment]
I am experiencing a similiar issue, the error message is: Integrity constraint violation: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '170' for key 'PRIMARY'

**Comment by mattmesker** [comment]
Having the same issue as @chromadesign on update:

`Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '455' for key 'PRIMARY'`

**Comment by mattmesker** [comment]
@chromadesign - I got the upgrade to work by deleting all rows remaining in the `simplemaps` table of your Craft database and re-running the update.

**Comment by alexbech** [comment]
Also having the same issue trying to upgrade from 3.3.5 to 3.4.8:

`Integrity constraint violation: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2020' for key 'PRIMARY'`

**Comment by RyanRoberts** [comment]
Had the exact same problem, thankfully it was just one entry I could remove from the db and continue with a successful migration. Basically it was falling over at the simplemap db record :(
