### ISSUE TITLE
Migration failure: Undefined index

### ISSUE THREAD

**Issue by elfacht** [ethercreative/simplemap#140]
Hi, while migration to production (staging worked fine) I got this while migration:

```
yii\base\ErrorException: Undefined index: countryRestriction

Migration: ether\simplemap\migrations\m190226_143809_craft3_upgrade

Output:

> Start map data upgrade
> drop table {{%simplemaps}} ... done (time: 0.007s)
> create table {{%simplemaps}} ... done (time: 0.008s)
> create unique index bnb_simplemaps_ownerId_ownerSiteId_fieldId_unq_idx on {{%simplemaps}} (ownerId,ownerSiteId,fieldId) ... done (time: 0.007s)
> create index bnb_simplemaps_lat_idx on {{%simplemaps}} (lat) ... done (time: 0.008s)
> create index bnb_simplemaps_lng_idx on {{%simplemaps}} (lng) ... done (time: 0.007s)
> add foreign key bnb_simplemaps_id_fk: {{%simplemaps}} (id) references {{%elements}} (id) ... done (time: 0.029s)
> add foreign key bnb_simplemaps_ownerId_fk: {{%simplemaps}} (ownerId) references {{%elements}} (id) ... done (time: 0.025s)
> add foreign key bnb_simplemaps_ownerSiteId_fk: {{%simplemaps}} (ownerSiteId) references {{%sites}} (id) ... done (time: 0.027s)
> add foreign key bnb_simplemaps_fieldId_fk: {{%simplemaps}} (fieldId) references {{%fields}} (id) ... done (time: 0.025s)
> Upgrade map value Alles Elbe, Hein-Hoyer-Straße, Hamburg, Deutschland
Exception: Undefined index: countryRestriction (/var/www/virtual/spillout/html/production/htdocs/app/vendor/ether/simplemap/src/migrations/m190226_143809_craft3_upgrade.php:242)
#0 /var/www/virtual/spillout/html/production/htdocs/app/vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/virtua...', 242)
#1 /var/www/virtual/spillout/html/production/htdocs/app/vendor/ether/simplemap/src/migrations/m190226_143809_craft3_upgrade.php(242): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/virtua...', 242, Array)
#2 /var/www/virtual/spillout/html/production/htdocs/app/vendor/ether/simplemap/src/migrations/m190226_143809_craft3_upgrade.php(50): ether\simplemap\migrations\m190226_143809_craft3_upgrade->_upgrade3()
#3 /var/www/virtual/spillout/html/production/htdocs/app/vendor/craftcms/cms/src/db/Migration.php(56): ether\simplemap\migrations\m190226_143809_craft3_upgrade->safeUp()
#4 /var/www/virtual/spillout/html/production/htdocs/app/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#5 /var/www/virtual/spillout/html/production/htdocs/app/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(ether\simplemap\migrations\m190226_143809_craft3_upgrade))
#6 /var/www/virtual/spillout/html/production/htdocs/app/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#7 /var/www/virtual/spillout/html/production/htdocs/app/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#8 /var/www/virtual/spillout/html/production/htdocs/app/vendor/craftcms/cms/src/controllers/UpdaterController.php(209): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#9 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#10 /var/www/virtual/spillout/html/production/htdocs/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/www/virtual/spillout/html/production/htdocs/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /var/www/virtual/spillout/html/production/htdocs/app/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#13 /var/www/virtual/spillout/html/production/htdocs/app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#14 /var/www/virtual/spillout/html/production/htdocs/app/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#15 /var/www/virtual/spillout/html/production/htdocs/app/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#16 /var/www/virtual/spillout/html/production/htdocs/app/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#17 /var/www/virtual/spillout/html/production/htdocs/app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/www/virtual/spillout/html/production/htdocs/app/web/index.php(21): yii\base\Application->run()
#19 {main}
```

**Comment by elfacht** [comment]
Ok, this is deprecated. Somehow it worked anyway. Sorry for bothering.

**Comment by tomdeleu** [comment]
I have the same exception when trying to upgrade to the latest version. Any thoughts on how to solve it?
