### ISSUE TITLE
3.4.4 -> 3.4.7 migration error

### ISSUE THREAD

**Issue by jamesedmonston** [ethercreative/simplemap#142]
### Description

Updating from 3.4.4 -> 3.4.7 causes a migration error.

```Integrity constraint violation: SQLSTATE[23503]: Foreign key violation: 7 ERROR: insert or update on table "simplemaps" violates foreign key constraint "simplemaps_id_fk"
DETAIL: Key (id)=(9) is not present in table "elements".
The SQL being executed was: INSERT INTO "simplemaps" ("id", "ownerId", "ownerSiteId", "fieldId", "lat", "lng", "zoom", "address", "parts", "dateCreated", "uid", "dateUpdated") VALUES (9, 814, 1, 31, '41.372879000', '2.154867000', 15, 'Crowne Plaza Barcelona Fira Center', '{"number":"","address":"","city":"","postcode":"","county":"","state":"","country":""}', '2019-03-26 12:46:01', '9fc481ff-ebc9-4f05-8be7-c3d146124d1a', '2019-03-26 12:46:01') RETURNING "id"

Migration: ether\simplemap\migrations\m190325_130533_repair_map_elements

Output:

> Start map data fix
> drop table {{%simplemaps}} ... done (time: 0.007s)
> create table {{%simplemaps}} ... done (time: 0.021s)
> create unique index simplemaps_ownerId_ownerSiteId_fieldId_unq_idx on {{%simplemaps}} (ownerId,ownerSiteId,fieldId) ... done (time: 0.005s)
> create index simplemaps_lat_idx on {{%simplemaps}} (lat) ... done (time: 0.005s)
> create index simplemaps_lng_idx on {{%simplemaps}} (lng) ... done (time: 0.005s)
> add foreign key simplemaps_id_fk: {{%simplemaps}} (id) references {{%elements}} (id) ... done (time: 0.009s)
> add foreign key simplemaps_ownerId_fk: {{%simplemaps}} (ownerId) references {{%elements}} (id) ... done (time: 0.004s)
> add foreign key simplemaps_ownerSiteId_fk: {{%simplemaps}} (ownerSiteId) references {{%sites}} (id) ... done (time: 0.099s)
> add foreign key simplemaps_fieldId_fk: {{%simplemaps}} (fieldId) references {{%fields}} (id) ... done (time: 0.004s)
> Fix map value 20 Rodborough Road, Frenchs Forest , NSW 2086, AUSTRALIA
> Fix map value Sheffield Winter Garden, 90 Surrey St, Sheffield S1 2LH
> Fix map value Westin St. Francis Hotel | San Francisco, California
> Fix map value HILTON SAN FRANCISCO UNION SQUARE, San Francisco, CA 94102 USA
> Fix map value E14 5AB
> Fix map value etc.venues 200 Aldersgate, London
> Fix map value 
> Fix map value Lotte New York Palace Hotel
> Fix map value Crowne Plaza Barcelona Fira Center
Exception: SQLSTATE[23503]: Foreign key violation: 7 ERROR: insert or update on table "simplemaps" violates foreign key constraint "simplemaps_id_fk"
DETAIL: Key (id)=(9) is not present in table "elements".
The SQL being executed was: INSERT INTO "simplemaps" ("id", "ownerId", "ownerSiteId", "fieldId", "lat", "lng", "zoom", "address", "parts", "dateCreated", "uid", "dateUpdated") VALUES (9, 814, 1, 31, '41.372879000', '2.154867000', 15, 'Crowne Plaza Barcelona Fira Center', '{"number":"","address":"","city":"","postcode":"","county":"","state":"","country":""}', '2019-03-26 12:46:01', '9fc481ff-ebc9-4f05-8be7-c3d146124d1a', '2019-03-26 12:46:01') RETURNING "id" (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO "si...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('INSERT INTO "si...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /var/www/html/vendor/yiisoft/yii2/db/pgsql/Schema.php(617): yii\db\Command->queryOne()
#4 /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php(555): yii\db\pgsql\Schema->insert('{{%simplemaps}}', Array)
#5 /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php(521): yii\db\ActiveRecord->insertInternal(NULL)
#6 /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(false, NULL)
#7 /var/www/html/vendor/ether/simplemap/src/migrations/m190325_130533_repair_map_elements.php(52): yii\db\BaseActiveRecord->save(false)
#8 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(56): ether\simplemap\migrations\m190325_130533_repair_map_elements->safeUp()
#9 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#10 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(ether\simplemap\migrations\m190325_130533_repair_map_elements))
#11 /var/www/html/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#12 /var/www/html/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#13 /var/www/html/vendor/craftcms/cms/src/controllers/UpdaterController.php(209): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#14 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#15 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#18 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#19 /var/www/html/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#20 /var/www/html/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#21 /var/www/html/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#22 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /var/www/html/web/index.php(21): yii\base\Application->run()
#24 {main}
```

### Additional info

- Craft version: 3.1.19
- SimpleMap version: 3.4.4
- PHP version: 7.3.2
- Database driver & version: Postgres 11.2
- Other Plugins:

**Comment by Tam** [comment]
Fixed in 3.4.8
