### ISSUE TITLE
Can't install Maps after updating Craft 2 to Craft 3 

### ISSUE THREAD

**Issue by artsigns** [ethercreative/simplemap#155]
### Description
After updating Craft 2 to Craft 3 can't install Maps.

### Steps to reproduce

1. Install Maps
2. Settings > Plugins shows `Not installed`

### Additional info

- Craft version:3.1.23
- Maps version:3.4.11
- PHP version:7.1.6
- Database driver & version:MySQL 5.5.5
- Other Plugins: Anchors, Craft Commerce. Freeform Lite, Freeform Pro, ImageOptimize, Imager, Incognito Field, Minify, Redactor, Retour, SEOmatic, Typogrify

**Comment by Tam** [comment]
@artsigns Can you check your logs to see if there were any errors upgrading?

**Comment by artsigns** [comment]
Here's what I get when I `./craft install/plugin simplemap` :
```*** installing simplemap
    > create table {{%simplemaps}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'craft_simplemaps' already exists
The SQL being executed was: CREATE TABLE `craft_simplemaps` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`ownerId` int(11) NOT NULL,
	`ownerSiteId` int(11),
	`fieldId` int(11) NOT NULL,
	`lat` decimal(11,9),
	`lng` decimal(12,9),
	`zoom` int(2),
	`address` varchar(255),
	`parts` text,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8 (/home/vagrant/sites/artsigns/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /home/vagrant/sites/artsigns/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `c...')
#1 /home/vagrant/sites/artsigns/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('CREATE TABLE `c...')
#2 /home/vagrant/sites/artsigns/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 /home/vagrant/sites/artsigns/vendor/ether/simplemap/src/migrations/Install.php(44): yii\db\Migration->createTable('{{%simplemaps}}', Array)
#4 /home/vagrant/sites/artsigns/vendor/craftcms/cms/src/db/Migration.php(56): ether\simplemap\migrations\Install->safeUp()
#5 /home/vagrant/sites/artsigns/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#6 /home/vagrant/sites/artsigns/vendor/craftcms/cms/src/base/Plugin.php(152): craft\db\MigrationManager->migrateUp(Object(ether\simplemap\migrations\Install))
#7 /home/vagrant/sites/artsigns/vendor/craftcms/cms/src/services/Plugins.php(520): craft\base\Plugin->install()
#8 /home/vagrant/sites/artsigns/vendor/craftcms/cms/src/console/controllers/InstallController.php(191): craft\services\Plugins->installPlugin('simplemap')
#9 [internal function]: craft\console\controllers\InstallController->actionPlugin('simplemap')
#10 /home/vagrant/sites/artsigns/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /home/vagrant/sites/artsigns/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /home/vagrant/sites/artsigns/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('plugin', Array)
#13 /home/vagrant/sites/artsigns/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('plugin', Array)
#14 /home/vagrant/sites/artsigns/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install/plugin', Array)
#15 /home/vagrant/sites/artsigns/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('install/plugin', Array)
#16 /home/vagrant/sites/artsigns/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install/plugin', Array)
#17 /home/vagrant/sites/artsigns/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#18 /home/vagrant/sites/artsigns/craft(43): yii\base\Application->run()
#19 {main}
*** installed simplemap successfully (time: 0.038s)```

**Comment by Tam** [comment]
@artsigns Make sure you're upgrading from your Craft 2 database, not re-running it on an already updated database.

**Comment by artsigns** [comment]
@Tam How would I do that? I only have one map. Is there any way I can just clean out the plugin and do a clean install?

**Comment by Tam** [comment]
If you only have one map, and don't mind manually transfering the data, you could uninstall the plugin in Craft 2, upgrade Craft, then re-install the plugin fresh in Craft 3 and re-add the data.

**Comment by artsigns** [comment]
Is there any way of doing it post Craft 2 update because I've since migrated the rest of the site and set up all the other new plugins in Craft 3.

**Comment by Tam** [comment]
You could drop the `craft_simplemaps` table. You shouldn't have an issues installing the plugin once that's gone.

**Comment by artsigns** [comment]
How about `craft_simplemaps_maps`? This shouldn't have any effect on the remaining plugins or craft installation should it?

**Comment by Tam** [comment]
It might do, worth deleting both just to be safe.

**Comment by artsigns** [comment]
Ok, dropped both tables and got it working. Also had to delete the old field and make a new map field. So for Migration, the only way to go from Craft 2 to Craft 3 is to run the migration in Craft 2 before updating?

**Comment by Tam** [comment]
It's good practice to update to the latest minor version before updating the major version. Closing this since it seems like your issue is solved.
