### ISSUE TITLE
Migration error when upgrading from 3.6.1 => 3.6.2.1

### ISSUE THREAD

**Issue by rungta** [ethercreative/simplemap#185]
### Description

Getting the following migration error:

```
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: fields'

in ./vendor/ether/simplemap/src/migrations/m190723_105637_fix_map_field_column_type.php:40

Stack trace:
#0 ./vendor/ether/simplemap/src/migrations/m190723_105637_fix_map_field_column_type.php(40): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '...', 40, Array)
#1 ./vendor/ether/simplemap/src/SimpleMap.php(48): ether\simplemap\migrations\m190723_105637_fix_map_field_column_type->safeUp()
#2 ./vendor/yiisoft/yii2/base/BaseObject.php(109): ether\simplemap\SimpleMap->init()
#3 ./vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#4 ./vendor/craftcms/cms/src/base/Plugin.php(127): yii\base\Module->__construct('simplemap', Object(craft\console\Application), Array)
#5 [internal function]: craft\base\Plugin->__construct('simplemap', Object(craft\console\Application), Array)
#6 ./vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#7 ./vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('ether\\simplemap...', Array, Array)
#8 ./vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('ether\\simplemap...', Array, Array)
#9 ./vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#10 ./vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins->createPlugin('simplemap', Array)
#11 ./vendor/craftcms/cms/src/base/ApplicationTrait.php(1323): craft\services\Plugins->loadPlugins()
#12 ./vendor/craftcms/cms/src/console/Application.php(65): craft\console\Application->_postInit()
#13 ./vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#14 ./vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#15 ./vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#16 ./vendor/craftcms/cms/src/console/Application.php(54): yii\console\Application->__construct(Array)
#17 [internal function]: craft\console\Application->__construct(Array)
#18 ./vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#19 ./vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\console\\A...', Array, Array)
#20 ./vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\console\\A...', Array, Array)
#21 ./vendor/craftcms/cms/bootstrap/bootstrap.php(248): yii\BaseYii::createObject(Array)
#22 ./vendor/craftcms/cms/bootstrap/console.php(34): require('...')
#23 ./craft(21): require('...')
#24 {main}
```

### Steps to reproduce

1. Install version 3.6.1
2. Enable the plugin
3. Update to 3.6.2.1
4. Run `./craft migrate/all`

### Additional info

- Craft version: 3.2.6
- Maps version: 3.6.1
- PHP version: 7.1.19
- Database driver & version: MySQL

**Comment by Tam** [comment]
Fixed in 3.6.2.2
