### ISSUE TITLE
Update from 3.4.11 to 3.6.4.3 database exception

### ISSUE THREAD

**Issue by paul-frost** [ethercreative/simplemap#206]
### Description
I have run update from the control panel and composer update ether/simplemap from the CL and get the same result:
Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_locationMap' in 'field list'
I tried running ./craft migrate/all but no effect.

I'm assuming that field_locationMap should have been created in the content table at some point during the update?

### Steps to reproduce

1. run update from the control panel or
2. .composer update ether/simplemap from the CL

### Additional info
This is running in Mamp Pro 4.5 on my laptop.
- Craft version:3.3.4.1
- Maps version:3.4.11
- PHP version:7.1.12
- Database driver & version:5.6.38
- Other Plugins:
    "craftcms/cms": "3.3.4.1",
    "vlucas/phpdotenv": "^2.4.0",
    "craftcms/redactor": "2.4.0",
    "ether/simplemap": "3.6.4.3",
    "aelvan/preparse-field": "v1.1.0",
    "verbb/image-resizer": "2.0.6",
    "lucasbares/craft-emailobfuscator": "2.1.0",
    "craftcms/contact-form": "2.2.5",
    "craftcms/contact-form-honeypot": "1.0.2",
    "hillholliday/craft-user-manual": "v2.0.2",
    "craftcms/feed-me": "4.1.2"

**Comment by stefanmf** [comment]
I am facing the exact same problem, updating from the same versions (3.4.11 to 3.6.4.3). Any help much appreciated.

Craft version: 3.1.29
PHP version: 7.2.16
Database: MySQL 5.7.19

Other plugins:
Ansel for Craft 	2.1.2
CP Field Inspect 	1.0.5
Expanded Singles 	1.0.7
Feed Me 	4.1.0
Field Labels 	1.1.2
Field Manager 	2.1.0
Imager 	v2.1.10
Knock Knock 	1.1.0
Maps 	3.4.11
Neo 	2.3.5
oEmbed 	1.1.6
Portal 	1.1.3
Redactor 	2.3.3.2
Super Table 	2.1.21

**Comment by Tam** [comment]
@paul-frost @stefanmf Could you share the full stack traces from the errors?

**Comment by stefanmf** [comment]
sure, here is a stack trace:
```
Status: Internal Server Error

Response: <pre>Exception (Database Exception) &#039;yii\db\Exception&#039; with message &#039;SQLSTATE[42S22]: Column not found: 1054 Unknown column &#039;content.field_projectData_mapLocation&#039; in &#039;field list&#039;
The SQL being executed was: SELECT users.password, elements.id, elements.fieldLayoutId, elements.uid, elements.enabled, elements.archived, elements.dateCreated, elements.dateUpdated, elements_sites.slug, elements_sites.uri, elements_sites.enabled AS enabledForSite, users.username, users.firstName, users.lastName, users.email, users.admin, users.locked, users.pending, users.suspended, users.lastLoginDate, users.lockoutDate, users.photoId, users.hasDashboard, content.id AS contentId, content.field_contact_additionaltitle, content.field_contentBuilder_alignment, content.field_contentBuilder_videoAuto, content.field_projectData_awards, content.field_contentBuilder_text, content.field_contentBuilder_caption, content.field_projectData_client, content.field_projectData_collaborators, content.field_contactInformation, content.field_projectDescription, content.field_contact_email, content.field_contentBuilder_imageFree, content.field_headerImage, content.field_headerImagePortraitFormat, content.field_contentBuilder_headline, content.field_invertLogoOnHeaderImage, content.field_contentBuilder_imageLandscape, content.field_projectData_location, content.field_projectData_mapLocation, content.field_news_date, content.field_contact_phone, content.field_contentBuilder_imagePortrait, content.field_projectData_program, content.field_projectColor, content.field_projectStatement, content.field_relatedProjectImportText, content.field_contentBuilder_size, content.field_projectData_size, content.field_contentBuilder_adjacentSize, content.field_size_3to6, content.field_contentBuilder_spacing, content.field_contentBuilder_imageSquare, content.field_contentBuilder_statement, content.field_projectData_team, content.field_extendedText, content.field_news_text, content.field_contact_title, content.field_videoLandscapeFormat, content.field_videoPortraitFormat, content.field_contentBuilder_videoSize, content.field_contentBuilder_video, content.field_projectData_year
FROM (SELECT elements.id AS elementsId, elements_sites.id AS elementsSitesId, content.id AS contentId
FROM elements elements
INNER JOIN users users ON users.id = elements.id
INNER JOIN elements_sites elements_sites ON elements_sites.elementId = elements.id
INNER JOIN content content ON content.elementId = elements.id
WHERE (elements_sites.siteId=&#039;1&#039;) AND (content.siteId=&#039;1&#039;) AND (elements.id=&#039;1&#039;) AND (elements.archived=FALSE) AND (elements.dateDeleted IS NULL)
ORDER BY users.username
LIMIT 1) subquery
INNER JOIN users users ON users.id = subquery.elementsId
INNER JOIN elements elements ON elements.id = subquery.elementsId
INNER JOIN elements_sites elements_sites ON elements_sites.id = subquery.elementsSitesId
INNER JOIN content content ON content.id = subquery.contentId
ORDER BY users.username&#039;

in /Users/webserver/craft/vendor/yiisoft/yii2/db/Schema.php:664

Stack trace:
#0 /Users/webserver/craft/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema-&gt;convertException(Object(PDOException), &#039;SELECT users....&#039;)
#1 /Users/webserver/craft/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command-&gt;internalExecute(&#039;SELECT users....&#039;)
#2 /Users/webserver/craft/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command-&gt;queryInternal(&#039;fetch&#039;, NULL)
#3 /Users/webserver/craft/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command-&gt;queryOne()
#4 /Users/webserver/craft/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query-&gt;one(NULL)
#5 /Users/webserver/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1220): craft\db\Query-&gt;one(NULL)
#6 /Users/webserver/craft/vendor/craftcms/cms/src/elements/User.php(366): craft\elements\db\ElementQuery-&gt;one()
#7 /Users/webserver/craft/vendor/yiisoft/yii2/web/User.php(690): craft\elements\User::findIdentity(&#039;1&#039;)
#8 /Users/webserver/craft/vendor/craftcms/cms/src/web/User.php(491): yii\web\User-&gt;renewAuthStatus()
#9 /Users/webserver/craft/vendor/yiisoft/yii2/web/User.php(192): craft\web\User-&gt;renewAuthStatus()
#10 /Users/webserver/craft/vendor/craftcms/cms/src/web/User.php(231): yii\web\User-&gt;getIdentity()
#11 /Users/webserver/craft/vendor/mmikkel/cp-field-inspect/src/CpFieldInspect.php(76): craft\web\User-&gt;getIsAdmin()
#12 /Users/webserver/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): mmikkel\cpfieldinspect\CpFieldInspect-&gt;init()
#13 /Users/webserver/craft/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject-&gt;__construct(Array)
#14 /Users/webserver/craft/vendor/craftcms/cms/src/base/Plugin.php(127): yii\base\Module-&gt;__construct(&#039;cp-field-inspec...&#039;, Object(craft\web\Application), Array)
#15 [internal function]: craft\base\Plugin-&gt;__construct(&#039;cp-field-inspec...&#039;, Object(craft\web\Application), Array)
#16 /Users/webserver/craft/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass-&gt;newInstanceArgs(Array)
#17 /Users/webserver/craft/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container-&gt;build(&#039;mmikkel\\cpfield...&#039;, Array, Array)
#18 /Users/webserver/craft/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container-&gt;get(&#039;mmikkel\\cpfield...&#039;, Array, Array)
#19 /Users/webserver/craft/vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#20 /Users/webserver/craft/vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins-&gt;createPlugin(&#039;cp-field-inspec...&#039;, Array)
#21 /Users/webserver/craft/vendor/craftcms/cms/src/base/ApplicationTrait.php(1239): craft\services\Plugins-&gt;loadPlugins()
#22 /Users/webserver/craft/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application-&gt;_postInit()
#23 /Users/webserver/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application-&gt;init()
#24 /Users/webserver/craft/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject-&gt;__construct(Array)
#25 /Users/webserver/craft/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application-&gt;__construct(Array)
#26 [internal function]: craft\web\Application-&gt;__construct(Array)
#27 /Users/webserver/craft/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass-&gt;newInstanceArgs(Array)
#28 /Users/webserver/craft/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container-&gt;build(&#039;craft\\web\\Appli...&#039;, Array, Array)
#29 /Users/webserver/craft/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container-&gt;get(&#039;craft\\web\\Appli...&#039;, Array, Array)
#30 /Users/webserver/craft/vendor/craftcms/cms/bootstrap/bootstrap.php(248): yii\BaseYii::createObject(Array)
#31 /Users/webserver/craft/vendor/craftcms/cms/bootstrap/web.php(52): require(&#039;/Users/webserver/c...&#039;)
#32 /Users/webserver/index.php(18): require(&#039;/Users/webserver/c...&#039;)
#33 {main}</pre>
```

**Comment by Tam** [comment]
@stefanmf From your stacktrace it looks like the `CP Field Inspect` plugin is causing the issue. Does the issue persist if you disable that plugin?
