### ISSUE TITLE
Database Migration Exception 3.3.5 => 3.6.4.3

### ISSUE THREAD

**Issue by kringkaste** [ethercreative/simplemap#207]
### Description
When updating the plugin from version 3.3.5 => 3.6.4.3 we get a database exception:

```
Exception: Invalid argument supplied for foreach() (/local/vendor/ether/simplemap/src/migrations/m190723_105637_fix_map_field_column_type.php:41)
#0 /local/vendor/ether/simplemap/src/migrations/m190723_105637_fix_map_field_column_type.php(41): yii\base\ErrorHandler->handleError(2, 'Invalid argumen...', '/local/vendor/e...', 41, Array)
#1 /local/vendor/craftcms/cms/src/db/Migration.php(56): ether\simplemap\migrations\m190723_105637_fix_map_field_column_type->safeUp()
#2 /local/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#3 /local/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(ether\simplemap\migrations\m190723_105637_fix_map_field_column_type))
#4 /local/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#5 /local/vendor/craftcms/cms/src/console/controllers/MigrateController.php(252): craft\services\Updates->runMigrations(Array)
#6 [internal function]: craft\console\controllers\MigrateController->actionAll()
#7 /local/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /local/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /local/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#10 /local/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#11 /local/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#12 /local/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#13 /local/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#14 /local/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#15 /local/craft(22): yii\base\Application->run()
#16 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Maps.'
```

### Steps to reproduce

1. composer update ether/simplemap
2. craft migrate/all

### Additional info

- Craft version: 3.1.34.3
- Maps version: 3.6.4.3
- PHP version: 7.0.33
- Database driver & version: 5.6.10
- Other Plugins:
    "codemonauts/craft-asset-autoversioning": "^1.0",
    "craftcms/aws-s3": "^1.0",
    "craftcms/redactor": "~2.1.7",
    "codemonauts/craft-healthz": "^1.0",
    "codemonauts/craft-instagram-feed": "^1.0.0",
    "mikestecker/craft-videoembedder": "^1.1",
    "verbb/super-table": "2.0.14",
    "dolphiq/iconpicker": "^1.0",
    "ether/simplemap": "^3.6",
    "dolphiq/redirect": "^1.0",
    "codemonauts/craft-customizable-radio-buttons-field": "^1.0.0",
    "nystudio107/craft-typogrify": "^1.1",
    "codemonauts/craft-redactor-nofollow": "^1.0"

**Comment by kringkaste** [comment]
Hey, just an update to this issue: We were able to update your plugin to version 3.5.2 on Craft ~3.1. Then we updated to Craft ~3.2 and tested again. The same error occurs. Then we updated to Craft ~3.3 and tested again. Same error again.

So we are now on Craft 3.3.5 and Map 3.5.2.
