### ISSUE TITLE
429 Too many request when running migration (3.4.8 -> 3.4.11)

### ISSUE THREAD

**Issue by Pautomagi** [ethercreative/simplemap#223]
### Description
Im running an upgrade from 3.3.3 to latest as an end goal here.
Currently been going upwards from 3.3.3-3.3.5-3.4.0-3.4.8-3.4.11

The migration failed on duplicates up until 3.4.11 so the migrations running now is from that release. It ran fine for a while but now its getting a 429 too many requests from openstreetmap.
I guess this is being used in the migration to validate some data or similar.

What good ways is there around this?

### Steps to reproduce

Steps to reproduce is hard to tell in this case. This is an older craft 2 install that has been upgraded to craft 3. The upgrade order has been sporadic and not always updated in time.
Hence why im getting in trouble for doing this upgrade as-is now.

### Additional info

- Craft version: 3.2.6
- Maps version: 3.4.11
- PHP version: 7.3
- Database driver & version: MySQL 5.7.28
- Other Plugins:

### Stack trace from failing migration

Just before this its trying an empty value address (I have a few in the database) as you can see by the api target/details.

```
Exception: Client error: `GET https://nominatim.openstreetmap.org/reverse?format=jsonv2&limit=1&addressdetails=1&accept-language=en&lat=0.00000000&lon=0.00000000` resulted in a `429 Too Many Requests` response:
<html>
<head>
<title>Bandwidth limit exceeded</title>
</head>
<body>
<h1>Bandwidth limit exceeded</h1>

<p>You have been (truncated...)
 (/var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('get', 'https://nominat...', Array)
#11 /var/www/html/vendor/ether/simplemap/src/services/GeoService.php(845): GuzzleHttp\Client->__call('get', Array)
#12 /var/www/html/vendor/ether/simplemap/src/services/GeoService.php(648): ether\simplemap\services\GeoService::_addressFromLatLng_Nominatim('0.00000000', '0.00000000')
#13 /var/www/html/vendor/ether/simplemap/src/services/MapService.php(361): ether\simplemap\services\GeoService::addressFromLatLng('0.00000000', '0.00000000')
#14 /var/www/html/vendor/ether/simplemap/src/services/MapService.php(146): ether\simplemap\services\MapService->_populateMissingData(Object(ether\simplemap\records\Map))
#15 /var/www/html/vendor/ether/simplemap/src/elements/Map.php(173): ether\simplemap\services\MapService->saveRecord(Object(ether\simplemap\elements\Map), '624', '1', '302', true)
#16 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(645): ether\simplemap\elements\Map->afterSave(true)
#17 /var/www/html/vendor/ether/simplemap/src/migrations/m190226_143809_craft3_upgrade.php(103): craft\services\Elements->saveElement(Object(ether\simplemap\elements\Map), false)
#18 /var/www/html/vendor/ether/simplemap/src/migrations/m190226_143809_craft3_upgrade.php(48): ether\simplemap\migrations\m190226_143809_craft3_upgrade->_upgrade2()
#19 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(56): ether\simplemap\migrations\m190226_143809_craft3_upgrade->safeUp()
#20 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#21 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(ether\simplemap\migrations\m190226_143809_craft3_upgrade))
#22 /var/www/html/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#23 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations(Array)
#24 [internal function]: craft\console\controllers\MigrateController->actionAll()
#25 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#26 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#27 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#28 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#29 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#30 /var/www/html/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#31 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#32 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#33 /var/www/html/craft(22): yii\base\Application->run()
#34 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Maps.'

in /var/www/html/vendor/craftcms/cms/src/services/Updates.php:233

Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#5 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /var/www/html/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#8 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /var/www/html/craft(22): yii\base\Application->run()
#11 {main}
```

**Comment by Pautomagi** [comment]
Coming to look at this, could it be if I set my GeoService to gmaps/mapbox where ive got a license/apikey that this would run as it should using that service?
(more rhetorical than anything, ill check back when ive tried this)

**Comment by Pautomagi** [comment]
Can confirm that setting the GeoService in `simplemap.php` to something ive got a key to fixes the 429 issue.
