### ISSUE TITLE
Error upgrading from version 3.5.2 to 3.7.5 Exception: Undefined offset

### ISSUE THREAD

**Issue by briancnoble** [ethercreative/simplemap#227]
### Description
Error occurs on **Step 3 Moving existing maps content**
Logs
```
1. Creating Maps content columns
- Create content column for Event - Location in content table
    > add column field_eventLocation text to table {{%content}} ... done (time: 11.791s)
- Create content column for Post - Location in content table
    > add column field_postLocation text to table {{%content}} ... done (time: 9.669s)
- Create content column for Marker in matrix pointOfInterest
    > add column field_pointOfInterest_marker text to table {{%matrixcontent_postblock}} ... done (time: 14.320s)
- Create content column for Location in matrix data
    > add column field_data_location text to table {{%matrixcontent_postpointofinteres}} ... done (time: 0.150s)
2. Creating new Maps table
    > create table {{%maps}} ... done (time: 0.041s)
    > create unique index maps_ownerId_ownerSiteId_fieldId_unq_idx on {{%maps}} (ownerId,ownerSiteId,fieldId) ... done (time: 0.044s)
    > create index maps_lat_idx on {{%maps}} (lat) ... done (time: 0.054s)
    > create index maps_lng_idx on {{%maps}} (lng) ... done (time: 0.043s)
    > add foreign key maps_ownerId_fk: {{%maps}} (ownerId) references {{%elements}} (id) ... done (time: 0.151s)
    > add foreign key maps_ownerSiteId_fk: {{%maps}} (ownerSiteId) references {{%sites}} (id) ... done (time: 0.156s)
    > add foreign key maps_fieldId_fk: {{%maps}} (fieldId) references {{%fields}} (id) ... done (time: 0.143s)
3. Moving existing maps content
- Moving Palma de Mallorca, España (5582) to {{%content}}
Exception: Undefined offset: 26 (/home/vagrant/code/affordablemallorca-com/vendor/ether/simplemap/src/migrations/m190712_104805_new_data_format.php:277)
#0 /home/vagrant/code/affordablemallorca-com/vendor/craftcms/cms/src/db/MigrationManager.php(239): ether\simplemap\migrations\m190712_104805_new_data_format->up('???')
#1 /home/vagrant/code/affordablemallorca-com/vendor/craftcms/cms/src/db/MigrationManager.php(159): craft\db\MigrationManager->migrateUp('???')
#2 /home/vagrant/code/affordablemallorca-com/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up('???')
#3 /home/vagrant/code/affordablemallorca-com/vendor/craftcms/cms/src/console/controllers/MigrateController.php(265): craft\services\Updates->runMigrations('???')
#4 /home/vagrant/code/affordablemallorca-com/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\console\controllers\MigrateController->actionAll()
#5 /home/vagrant/code/affordablemallorca-com/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/home/vagrant/code/affordablemallorca-com/vendor/yiisoft/yii2/base/InlineAction.php:57}('???', '???')
#6 /home/vagrant/code/affordablemallorca-com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams('???')
#7 /home/vagrant/code/affordablemallorca-com/vendor/yiisoft/yii2/console/Controller.php(148): craft\console\controllers\MigrateController->runAction('???', '???')
#8 /home/vagrant/code/affordablemallorca-com/vendor/yiisoft/yii2/base/Module.php(528): craft\console\controllers\MigrateController->runAction('???', '???')
#9 /home/vagrant/code/affordablemallorca-com/vendor/yiisoft/yii2/console/Application.php(180): craft\console\Application->runAction('???', '???')
#10 /home/vagrant/code/affordablemallorca-com/vendor/craftcms/cms/src/console/Application.php(93): craft\console\Application->runAction('???', '???')
#11 /home/vagrant/code/affordablemallorca-com/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('???', '???')
#12 /home/vagrant/code/affordablemallorca-com/vendor/yiisoft/yii2/base/Application.php(386): craft\console\Application->handleRequest('???')
#13 /home/vagrant/code/affordablemallorca-com/craft(22): craft\console\Application->run()
#14 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Maps.'
```
### Steps to reproduce

1. run composer require new version
2. go to site admin
3. immediately see SQL column not found error
4. run `craft migrate/all`

### Additional info

- Craft version: "3.3.15"
- Maps version: "3.5.2"
- PHP version: "7.1"
- Database driver & version:  5.7.27-0ubuntu0.18.04.1 
- Other Plugins:
``` 
"briancnoble/return-type": "^1.0",  
    "vlucas/phpdotenv": "^2.4.0",
    "nystudio107/craft-disqus": "1.1.2",
    "craftcms/redactor": "2.4.0",
    "craftcms/element-api": "2.6.0",
    "verbb/expanded-singles": "1.0.7", 
    "wbrowar/contentstats": "2.1.1",
    "aelvan/inlin": "2.1.1",
    "charliedev/section-field": "1.1.0",
    "mikestecker/craft-videoembedder": "1.1.4",
    "mmikkel/incognito-field": "1.1.1.1",
    "verbb/feed-me": "3.0.0-beta.13",
    "craftcms/contact-form": "2.2.5",
    "craftcms/contact-form-honeypot": "1.0.2",
    "matt-west/craft-recaptcha": "1.3.0",
    "enupal/translate": "1.2.0",
    "nystudio107/craft-seomatic": "3.2.33",
    "craftcms/anchors": "2.2.0",
    "benjamminf/craft-embedded-assets": "1.0.2",
    "solspace/craft3-calendar": "2.0.25",
    "verbb/super-table": "2.3.0",
    "spicyweb/craft-embedded-assets": "2.1.1.1",
    "nystudio107/craft-retour": "3.1.27"
```

**Comment by Tam** [comment]
@briancnoble Can you email a database dump to dev@ethercreative.co.uk? Also, am I correct in thinking you're using MySQL?

**Comment by briancnoble** [comment]
Yes we're use MySQL.  No problem giving you a DB dump.  Would you be willing to sign an NDA?

**Comment by Tam** [comment]
@briancnoble I've pushed a fix for your issue. You also have an errant `maps` table in your database, you'll want to drop that before migrating.
