### ISSUE TITLE
Database Exception: "Duplicate key on write or update" in m190712_104805_new_data_format

### ISSUE THREAD

**Issue by roberttolton** [ethercreative/simplemap#232]
### Description

Am running a dry-run of an update to a production site, locally. It is going from Craft 3.0.41.1 to Craft 3.3.15

Simple map is going from 3.3.5 to 3.7.2

Error:

```
Database Exception: SQLSTATE[HY000]: General error: 1005 Can't create table website_craft.#sql-567_2e1 (errno: 121 "Duplicate key on write or update")
The SQL being executed was: ALTER TABLE craft_maps ADD CONSTRAINT craft_maps_ownerId_fk FOREIGN KEY (ownerId) REFERENCES craft_elements (id) ON DELETE CASCADE

Migration: ether\simplemap\migrations\m190712_104805_new_data_format

Output:

1. Creating Maps content columns
- Create content column for Map Module Map in matrix mapModule
> add column field_mapModule_mapModuleMap text to table {{%matrixcontent_importedmodules}} ... done (time: 4.024s)
- Create content column for Map Module Map in matrix mapModule
> add column field_mapModule_mapModuleMap text to table {{%matrixcontent_modules}} ... done (time: 0.004s)
2. Creating new Maps table
> drop index craft_maps_ownerId_ownerSiteId_fieldId_unq_idx on {{%maps}} ... done (time: 0.010s)
> drop index craft_maps_lat_idx on {{%maps}} ... done (time: 0.005s)
> drop index craft_maps_lng_idx on {{%maps}} ... done (time: 0.004s)
> drop index craft_maps_ownerSiteId_fk on {{%maps}} ... done (time: 0.004s)
> drop index craft_maps_fieldId_fk on {{%maps}} ... done (time: 0.007s)
> rename table {{%maps}} to {{%simplemaps}} ... done (time: 3.298s)
> create table {{%maps}} ... done (time: 0.007s)
> create unique index craft_maps_ownerId_ownerSiteId_fieldId_unq_idx on {{%maps}} (ownerId,ownerSiteId,fieldId) ... done (time: 0.007s)
> create index craft_maps_lat_idx on {{%maps}} (lat) ... done (time: 0.010s)
> create index craft_maps_lng_idx on {{%maps}} (lng) ... done (time: 0.010s)
> add foreign key craft_maps_ownerId_fk: {{%maps}} (ownerId) references {{%elements}} (id) ...Exception: SQLSTATE[HY000]: General error: 1005 Can't create table website_craft.#sql-567_2e1 (errno: 121 "Duplicate key on write or update")
The SQL being executed was: ALTER TABLE craft_maps ADD CONSTRAINT craft_maps_ownerId_fk FOREIGN KEY (ownerId) REFERENCES craft_elements (id) ON DELETE CASCADE (/vagrant/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /vagrant/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /vagrant/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('ALTER TABLE cr...')
#2 /vagrant/vendor/yiisoft/yii2/db/Migration.php(467): yii\db\Command->execute()
#3 /vagrant/vendor/craftcms/cms/src/db/Migration.php(373): yii\db\Migration->addForeignKey('craft_maps_owne...', '{{%maps}}', Array, '{{%elements}}', Array, 'CASCADE', NULL)
#4 /vagrant/vendor/ether/simplemap/src/migrations/Install.php(74): craft\db\Migration->addForeignKey('craft_maps_owne...', '{{%maps}}', Array, '{{%elements}}', Array, 'CASCADE')
#5 /vagrant/vendor/ether/simplemap/src/migrations/m190712_104805_new_data_format.php(246): ether\simplemap\migrations\Install->safeUp()
#6 /vagrant/vendor/craftcms/cms/src/db/Migration.php(58): ether\simplemap\migrations\m190712_104805_new_data_format->safeUp()
#7 /vagrant/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
#8 /vagrant/vendor/craftcms/cms/src/db/MigrationManager.php(159): craft\db\MigrationManager->migrateUp(Object(ether\simplemap\migrations\m190712_104805_new_data_format))
#9 /vagrant/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#10 /vagrant/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#11 /vagrant/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#12 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#13 /vagrant/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /vagrant/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /vagrant/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('migrate', Array)
#16 /vagrant/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#17 /vagrant/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('updater/migrate', Array)
#18 /vagrant/vendor/craftcms/cms/src/web/Application.php(652): craft\web\Application->runAction('updater/migrate')
#19 /vagrant/vendor/craftcms/cms/src/web/Application.php(231): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#20 /vagrant/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /vagrant/web/index.php(43): yii\base\Application->run()
#22 {main}
```

### Steps to reproduce

1. Install Craft 3.0.41.1
2. Install Simple Map 3.3.5
3. Update Craft to 3.3.15 and Simple Map to 3.7.2 via Composer
4. Visit Dashboard to run migrations

### Additional info

- Craft version: 3.0.41.1
- Maps version: 3.3.5
- PHP version: 7.2.9
- Database driver & version: MariaDB 10.3.9 (MySql 5.5.5)
- Other Plugins: 
```
    "vlucas/phpdotenv": "^2.4.0",
    "clubstudioltd/craft-asset-rev": "6.0.2",
    "wbrowar/contentstats": "2.1.1",
    "aelvan/imager": "v2.1.10",
    "fruitstudios/linkit": "1.1.6",
    "aelvan/preparse-field": "v1.0.6",
    "nystudio107/craft-seomatic": "3.2.4",
    "craftcms/simple-text": "2.0.2",
    "verbb/super-table": "2.0.14",
    "craftcms/redactor": "2.1.7",
    "ether/simplemap": "3.3.5",
    "aelvan/craft-cp-element-count": "v1.0.1",
    "verbb/navigation": "1.1.8",
    "supercool/buttonbox": "2.0.3",
    "putyourlightson/craft-blitz": "1.11.5",
    "pierrestoffe/craft-language-redirector": "1.1.3",
    "dolphiq/redirect": "1.0.23",
    "topshelfcraft/environment-label": "3.1.5",
    "nystudio107/craft-minify": "1.2.9",
    "mmikkel/cp-clearcache": "1.0.4",
    "ether/logs": "v3.0.0",
    "barrelstrength/sprout-fields": "3.2.1",
    "nystudio107/craft-cookies": "1.1.11",
    "culturejapanmirai/mirai": "*",
    "ether/tags": "1.0.3",
    "doublesecretagency/craft-cpcss": "2.1.0",
    "craftcms/element-api": "2.5.4",
    "frontwise/craft-monitor404": "v1.1.0",
    "superbig/craft3-bugsnag": "2.0.4",
    "ostark/craft-async-queue": "2.0.0",
    "lukeyouell/craft-queue-manager": "1.1.0",
    "indigoviking/jsond": "1.05"
```

**Comment by roberttolton** [comment]
Have also tried updating to the latest versions of everything, straight from a copy of my production environment via the Updates section of the Dashboard.

Migrations failed with a different error:

```
Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'zoom' in 'field list'
The SQL being executed was: SELECT id, ownerId, ownerSiteId, fieldId, lat, lng, zoom, address, parts
FROM craft_simplemaps
WHERE (ownerId='1') AND (ownerSiteId='1')
GROUP BY id, fieldId
ORDER BY dateUpdated

Migration: ether\simplemap\migrations\m190712_104805_new_data_format

Output:

1. Creating Maps content columns
- Create content column for Map Module Map in matrix mapModule
> add column field_mapModule_mapModuleMap text to table {{%matrixcontent_importedmodules}} ... done (time: 0.003s)
- Create content column for Map Module Map in matrix mapModule
> add column field_mapModule_mapModuleMap text to table {{%matrixcontent_modules}} ... done (time: 0.002s)
2. Creating new Maps table
> drop index craft_maps_ownerId_ownerSiteId_fieldId_unq_idx on {{%maps}} ... done (time: 0.005s)
> drop index craft_maps_lat_idx on {{%maps}} ... done (time: 0.004s)
> drop index craft_maps_lng_idx on {{%maps}} ... done (time: 0.004s)
> rename table {{%maps}} to {{%simplemaps}} ... done (time: 0.004s)
> create table {{%maps}} ... done (time: 0.008s)
> create unique index craft_maps_ownerId_ownerSiteId_fieldId_unq_idx on {{%maps}} (ownerId,ownerSiteId,fieldId) ... done (time: 0.008s)
> create index craft_maps_lat_idx on {{%maps}} (lat) ... done (time: 0.009s)
> create index craft_maps_lng_idx on {{%maps}} (lng) ... done (time: 0.010s)
> add foreign key craft_maps_ownerId_fk: {{%maps}} (ownerId) references {{%elements}} (id) ... done (time: 0.027s)
> add foreign key craft_maps_ownerSiteId_fk: {{%maps}} (ownerSiteId) references {{%sites}} (id) ... done (time: 0.019s)
> add foreign key craft_maps_fieldId_fk: {{%maps}} (fieldId) references {{%fields}} (id) ... done (time: 0.017s)
3. Moving existing maps content
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'zoom' in 'field list'
The SQL being executed was: SELECT id, ownerId, ownerSiteId, fieldId, lat, lng, zoom, address, parts
FROM craft_simplemaps
WHERE (ownerId='1') AND (ownerSiteId='1')
GROUP BY id, fieldId
ORDER BY dateUpdated (/vagrant/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /vagrant/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT id, o...')
#1 /vagrant/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT id, o...')
#2 /vagrant/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /vagrant/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /vagrant/vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
#5 /vagrant/vendor/ether/simplemap/src/migrations/m190712_104805_new_data_format.php(488): craft\db\Query->all()
#6 /vagrant/vendor/ether/simplemap/src/migrations/m190712_104805_new_data_format.php(261): ether\simplemap\migrations\m190712_104805_new_data_format->_getMapContent('1', '1')
#7 /vagrant/vendor/craftcms/cms/src/db/Migration.php(58): ether\simplemap\migrations\m190712_104805_new_data_format->safeUp()
#8 /vagrant/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
#9 /vagrant/vendor/craftcms/cms/src/db/MigrationManager.php(159): craft\db\MigrationManager->migrateUp(Object(ether\simplemap\migrations\m190712_104805_new_data_format))
#10 /vagrant/vendor/craftcms/cms/src/services/Updates.php(238): craft\db\MigrationManager->up()
#11 /vagrant/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(522): craft\services\Updates->runMigrations(Array)
#12 /vagrant/vendor/craftcms/cms/src/controllers/UpdaterController.php(209): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#13 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#14 /vagrant/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /vagrant/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /vagrant/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('migrate', Array)
#17 /vagrant/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#18 /vagrant/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('updater/migrate', Array)
#19 /vagrant/vendor/craftcms/cms/src/web/Application.php(652): craft\web\Application->runAction('updater/migrate')
#20 /vagrant/vendor/craftcms/cms/src/web/Application.php(251): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#21 /vagrant/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /vagrant/web/index.php(43): yii\base\Application->run()
#23 {main}
```

**Comment by roberttolton** [comment]
I tried the comment within the update docs that mentioned running `craft migrate/all` but that also failed:

```
vagrant@craft-3:/vagrant$ ./craft migrate/all
Yii Migration Tool (based on Yii v2.0.30)

1. Creating Maps content columns
- Create content column for Map Module Map in matrix mapModule
    > alter column field_mapModule_mapModuleMap in table {{%matrixcontent_importedmodules}} to text ... done (time: 0.268s)
- Create content column for Map Module Map in matrix mapModule
    > alter column field_mapModule_mapModuleMap in table {{%matrixcontent_modules}} to text ... done (time: 0.001s)
2. Creating new Maps table
    > drop index craft_maps_ownerId_ownerSiteId_fieldId_unq_idx on {{%maps}} ... done (time: 0.035s)
    > drop index craft_maps_lat_idx on {{%maps}} ... done (time: 0.012s)
    > drop index craft_maps_lng_idx on {{%maps}} ... done (time: 2.572s)
    > drop index craft_maps_ownerSiteId_fk on {{%maps}} ... done (time: 0.006s)
    > drop index craft_maps_fieldId_fk on {{%maps}} ... done (time: 0.004s)
    > rename table {{%maps}} to {{%simplemaps}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'craft_simplemaps' already exists
The SQL being executed was: RENAME TABLE `craft_maps` TO `craft_simplemaps` (/vagrant/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /vagrant/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'RENAME TABLE `c...')
#1 /vagrant/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('RENAME TABLE `c...')
#2 /vagrant/vendor/yiisoft/yii2/db/Migration.php(340): yii\db\Command->execute()
#3 /vagrant/vendor/ether/simplemap/src/migrations/m190712_104805_new_data_format.php(243): yii\db\Migration->renameTable('{{%maps}}', '{{%simplemaps}}')
#4 /vagrant/vendor/craftcms/cms/src/db/Migration.php(58): ether\simplemap\migrations\m190712_104805_new_data_format->safeUp()
#5 /vagrant/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
#6 /vagrant/vendor/craftcms/cms/src/db/MigrationManager.php(159): craft\db\MigrationManager->migrateUp(Object(ether\simplemap\migrations\m190712_104805_new_data_format))
#7 /vagrant/vendor/craftcms/cms/src/services/Updates.php(238): craft\db\MigrationManager->up()
#8 /vagrant/vendor/craftcms/cms/src/console/controllers/MigrateController.php(265): craft\services\Updates->runMigrations(Array)
#9 [internal function]: craft\console\controllers\MigrateController->actionAll()
#10 /vagrant/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /vagrant/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /vagrant/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#13 /vagrant/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#14 /vagrant/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#15 /vagrant/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#16 /vagrant/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#17 /vagrant/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#18 /vagrant/craft(43): yii\base\Application->run()
#19 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Maps.'

in /vagrant/vendor/craftcms/cms/src/services/Updates.php:246

Stack trace:
#0 /vagrant/vendor/craftcms/cms/src/console/controllers/MigrateController.php(265): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /vagrant/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /vagrant/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /vagrant/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#5 /vagrant/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /vagrant/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /vagrant/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#8 /vagrant/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /vagrant/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /vagrant/craft(43): yii\base\Application->run()
#11 {main}
```

**Comment by Tam** [comment]
Could you email a copy of your database to dev@ethercreative.co.uk?

**Comment by roberttolton** [comment]
@Tam Unfortunately I don't have a copy from that time anymore, I ended up just uninstalling and re-installing.
