### ISSUE TITLE
Setting unknown property: ether\simplemap\models\Map::__placeId

### ISSUE THREAD

**Issue by krizzzly** [ethercreative/simplemap#242]
### Description

```
yii\base\UnknownPropertyException: Setting unknown property: ether\simplemap\models\Map::__placeId in /www/binder/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /www/binder/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('__placeId', 'ChIJV-x84si5kUc...')
#1 /www/binder/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(ether\simplemap\models\Map), Array)
#2 /www/binder/vendor/ether/simplemap/src/models/BaseLocation.php(47): yii\base\BaseObject->__construct(Array)
#3 /www/binder/vendor/ether/simplemap/src/models/Map.php(55): ether\simplemap\models\BaseLocation->__construct(Array)
#4 /www/binder/vendor/ether/simplemap/src/fields/MapField.php(242): ether\simplemap\models\Map->__construct(Array)
#5 /www/binder/vendor/craftcms/cms/src/base/Element.php(2675): ether\simplemap\fields\MapField->normalizeValue(Array, Object(craft\elements\Entry))
#6 /www/binder/vendor/craftcms/cms/src/base/Element.php(2279): craft\base\Element->normalizeFieldValue('placeGps3')
#7 /www/binder/vendor/craftcms/cms/src/controllers/EntriesController.php(715): craft\base\Element->setFieldValuesFromRequest('fields')
#8 /www/binder/vendor/craftcms/cms/src/controllers/EntriesController.php(356): craft\controllers\EntriesController->_populateEntryModel(Object(craft\elements\Entry))
#9 [internal function]: craft\controllers\EntriesController->actionSaveEntry(false)
#10 /www/binder/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /www/binder/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /www/binder/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('save-entry', Array)
#13 /www/binder/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#14 /www/binder/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('entries/save-en...', Array)
#15 /www/binder/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('entries/save-en...', Array)
#16 /www/binder/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /www/binder/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /www/binder/web/index.php(21): yii\base\Application->run()
#19 {main}
```
### Steps to reproduce

1. using Google Maps, Places, Geolocation with API Key
2. adding a maps field to a section
3. new entry, define address, the place gets found, error when saving the entry

### Additional info

- Craft version: 3.4
- Maps version: latest LITE
- PHP version: 7.2.22
- Database driver & version: MySQL
- Other Plugins:

**Comment by krizzzly** [comment]
`vendor/ether/simplemap/src/models/BaseLocation.php:47` adding 
```
unset($config["__placeId"]);
```
fixes it for now.

**Comment by philipboomy** [comment]
Yeah I getting this too. The above fix works for me too.

**Comment by krizzzly** [comment]
to store the placeId would be very handy. greetings.

**Comment by jdsimcoe** [comment]
I'm still getting this bug. Is a fix for this forthcoming?

**Comment by adamhenretty** [comment]
The "fix" didn't fix for me. I can however drag and drop the pin on the map in the desired location to save the entry, just not via the address search.

**Comment by mattmesker** [comment]
I'm still getting this bug, too. Can we get a fix please?

**Comment by krizzzly** [comment]
ok the bug is fixed, but how can i access the Place Id now ?

**Comment by sidedwards** [comment]
`unset($config["__placeId"]);` fixed it for me but can we get an official fix in the next release?

**Comment by jdsimcoe** [comment]
This was already fixed in the release above.
