### ISSUE TITLE
Incorrect parameter count in the call to native function 'RADIANS'

### ISSUE THREAD

**Issue by timkelty** [ethercreative/simplemap#245]
Stack Trace:

```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1582 Incorrect parameter count in the call to native function 'RADIANS' in /app/vendor/composer/yiisoft/yii2/db/Command.php:1290
Stack trace:
#0 /app/vendor/composer/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute()
#1 /app/vendor/composer/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT EXISTS(S...')
#2 /app/vendor/composer/yiisoft/yii2/db/Command.php(425): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /app/vendor/composer/yiisoft/yii2/db/Query.php(433): yii\db\Command->queryScalar()
#4 /app/vendor/composer/craftcms/cms/src/db/Query.php(214): yii\db\Query->exists(NULL)
#5 /app/vendor/composer/craftcms/cms/src/elements/db/ElementQuery.php(1520): craft\db\Query->exists(NULL)
#6 /app/vendor/composer/twig/twig/src/Extension/CoreExtension.php(1499): craft\elements\db\ElementQuery->exists()
#7 /app/vendor/composer/craftcms/cms/src/helpers/Template.php(96): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\EntryQuery), 'exists', Array, 'method', false, false)
#8 /app/storage/runtime/compiled_templates/ae/ae1db23960e6cdc2aab1d889e263b119fce3451c280d0c9d3411aa4b6b89beb3.php(95): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\EntryQuery), 'exists', Array, 'method')
#9 /app/vendor/composer/twig/twig/src/Template.php(184): __TwigTemplate_4c8cd642af2b1f864f37dbe0d2b70e92e54355482d6c63f0ebd1f81548de44cf->block_main(Array, Array)
#10 /app/storage/runtime/compiled_templates/77/77b6ca3566966a9642b220d1112d1311093c1ab129cf7273b35829125aef9ab8.php(197): Twig\Template->displayBlock('main', Array, Array)
#11 /app/vendor/composer/twig/twig/src/Template.php(184): __TwigTemplate_8a8e6f9c80b54b44a5afc9bea08ab3b1ddd27f56477f023802e492fdab570081->block_htmlBody(Array, Array)
#12 /app/storage/runtime/compiled_templates/77/77b6ca3566966a9642b220d1112d1311093c1ab129cf7273b35829125aef9ab8.php(96): Twig\Template->displayBlock('htmlBody', Array, Array)
#13 /app/vendor/composer/twig/twig/src/Template.php(407): __TwigTemplate_8a8e6f9c80b54b44a5afc9bea08ab3b1ddd27f56477f023802e492fdab570081->doDisplay(Array, Array)
#14 /app/vendor/composer/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /app/storage/runtime/compiled_templates/ae/ae1db23960e6cdc2aab1d889e263b119fce3451c280d0c9d3411aa4b6b89beb3.php(50): Twig\Template->display(Array, Array)
#16 /app/vendor/composer/twig/twig/src/Template.php(407): __TwigTemplate_4c8cd642af2b1f864f37dbe0d2b70e92e54355482d6c63f0ebd1f81548de44cf->doDisplay(Array, Array)
#17 /app/vendor/composer/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /app/vendor/composer/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#19 /app/vendor/composer/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#20 /app/vendor/composer/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#21 /app/vendor/composer/craftcms/cms/src/web/View.php(397): Twig\Environment->render('_classifieds/en...', Array)
#22 /app/vendor/composer/craftcms/cms/src/web/View.php(458): craft\web\View->renderTemplate('_classifieds/en...', Array)
#23 /app/vendor/composer/craftcms/cms/src/web/Controller.php(235): craft\web\View->renderPageTemplate('_classifieds/en...', Array, 'site')
#24 /app/vendor/composer/craftcms/cms/src/controllers/TemplatesController.php(98): craft\web\Controller->renderTemplate('_classifieds/en...', Array)
#25 [internal function]: craft\controllers\TemplatesController->actionRender('_classifieds/en...', Array)
#26 /app/vendor/composer/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#27 /app/vendor/composer/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#28 /app/vendor/composer/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('render', Array)
#29 /app/vendor/composer/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#30 /app/vendor/composer/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('templates/rende...', Array)
#31 /app/vendor/composer/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#32 /app/vendor/composer/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#33 /app/vendor/composer/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#34 /app/public/index.php(5): yii\base\Application->run()
#35 {main}

Next yii\db\Exception: SQLSTATE[42000]: Syntax error or access violation: 1582 Incorrect parameter count in the call to native function 'RADIANS'
The SQL being executed was: SELECT EXISTS(SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `entries`.`sectionId`, `entries`.`typeId`, `entries`.`authorId`, `entries`.`postDate`, `entries`.`expiryDate`, `content`.`id` AS `contentId`, `content`.`title`, `content`.`field_activeCustomer`, `content`.`field_addStripe`, `content`.`field_additionalAttributesTable`, `content`.`field_algoliaSearchFilter`, `content`.`field_alignment`, `content`.`field_imgAltText`, `content`.`field_authorName`, `content`.`field_bodyOfWaterText`, `content`.`field_boldText`, `content`.`field_buttonText`, `content`.`field_buyDirectUrl`, `content`.`field_catalogUrl`, `content`.`field_classifiedType`, `content`.`field_clothingSize`, `content`.`field_code`, `content`.`field_condition`, `content`.`field_conditionsNotes`, `content`.`field_productConfigName`, `content`.`field_contactConsent`, `content`.`field_dealerLocatorUrl`, `content`.`field_departureMonths`, `content`.`field_richText`, `content`.`field_displayName`, `content`.`field_pfdEntryStyle`, `content`.`field_eventTrackingEnabled`, `content`.`field_eventTrackingAction`, `content`.`field_eventTrackingCategory`, `content`.`field_eventTrackingLabel`, `content`.`field_featured`, `content`.`field_firstName`, `content`.`field_fixedImageHeight`, `content`.`field_newGearLink`, `content`.`field_gearNotes`, `content`.`field_groupRates`, `content`.`field_headerTagline`, `content`.`field_heading`, `content`.`field_imageSize`, `content`.`field_productImageType`, `content`.`field_importedCreatedDate`, `content`.`field_importedEmail`, `content`.`field_italicText`, `content`.`field_lastName`, `content`.`field_legacyId`, `content`.`field_legacyIdAccessoryManufacturer`, `content`.`field_legacyIdBoards`, `content`.`field_legacyIdCanoes`, `content`.`field_legacyIdKayaks`, `content`.`field_legacyIdReviewManufacturer`, `content`.`field_legacyIdSupManufacturer`, `content`.`field_legacyIdSupReviews`, `content`.`field_legacyPlaceId`, `content`.`field_legacyIdProducts`, `content`.`field_tnplink`, `content`.`field_mapField`, `content`.`field_manufacturerName`, `content`.`field_manufacturerPdpUrl`, `content`.`field_manufacturerProductId`, `content`.`field_manufacturerUrl`, `content`.`field_materialDescription`, `content`.`field_maxCapacity`, `content`.`field_notes`, `content`.`field_numberOfPortages`, `content`.`field_outfitterTripDetailUrl`, `content`.`field_outfitterUrl`, `content`.`field_overlayTextEnabled`, `content`.`field_pageTemplate`, `content`.`field_parkingInfoAndFees`, `content`.`field_phoneNumber`, `content`.`field_portageDescription`, `content`.`field_price`, `content`.`field_pricePerPerson`, `content`.`field_productName`, `content`.`field_productOption`, `content`.`field_productStatus`, `content`.`field_promoLink`, `content`.`field_radius`, `content`.`field_reviewRating`, `content`.`field_releaseDate`, `content`.`field_safetyNotes`, `content`.`field_seoMeta`, `content`.`field_seomaticMeta`, `content`.`field_showInTripFinder`, `content`.`field_subtitle`, `content`.`field_tripDuration`, `content`.`field_tripStatus`, `content`.`field_tripType`, `content`.`field_uscgType`, `content`.`field_volume`, `content`.`field_warehouseLocation`, `content`.`field_weightLbs`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`, (111.045 *DEGREES(ACOS(COS(RADIANS()) *COS(RADIANS(`maps_mapField`.`lat`)) *COS(RADIANS() - RADIANS(`maps_mapField`.`lng`)) +SIN(RADIANS()) *SIN(RADIANS(`maps_mapField`.`lat`))))) as `mapsCalculatedDistance`
FROM `craft_elements` `elements`
INNER JOIN `craft_entries` `entries` ON `entries`.`id` = `elements`.`id`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `craft_content` `content` ON `content`.`elementId` = `elements`.`id`
JOIN `craft_maps` `maps_mapField` ON (`elements`.`id` = `maps_mapField`.`ownerId`) AND (`elements`.`dateDeleted` IS NULL) AND (`elements_sites`.`siteId` = `maps_mapField`.`ownerSiteId`) AND (`maps_mapField`.`fieldId` = 395)
WHERE (`entries`.`sectionId`='24') AND (((`maps_mapField`.`lat` >=  - (5000 / 111.045)) AND (`maps_mapField`.`lat` <=  + (5000 / 111.045))) AND ((`maps_mapField`.`lng` >=  - (5000 / (111.045 * COS(RADIANS())))) AND (`maps_mapField`.`lng` <=  + (5000 / (111.045 * COS(RADIANS())))))) AND (NOT (`elements`.`id`='581859')) AND (`elements`.`archived`=FALSE) AND (((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (`entries`.`postDate` <= '2020-03-12 13:47:00') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2020-03-12 13:47:00'))) AND (`elements`.`dateDeleted` IS NULL) AND (`elements_sites`.`enabled`=TRUE) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)
HAVING `mapsCalculatedDistance` <= 5000
ORDER BY `mapsCalculatedDistance`
LIMIT 3) `subquery`
INNER JOIN `craft_entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `craft_content` `content` ON `content`.`id` = `subquery`.`contentId`
ORDER BY `mapsCalculatedDistance`) in /app/vendor/composer/yiisoft/yii2/db/Schema.php:674
Stack trace:
#0 /app/vendor/composer/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT EXISTS(S...')
#1 /app/vendor/composer/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT EXISTS(S...')
#2 /app/vendor/composer/yiisoft/yii2/db/Command.php(425): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /app/vendor/composer/yiisoft/yii2/db/Query.php(433): yii\db\Command->queryScalar()
#4 /app/vendor/composer/craftcms/cms/src/db/Query.php(214): yii\db\Query->exists(NULL)
#5 /app/vendor/composer/craftcms/cms/src/elements/db/ElementQuery.php(1520): craft\db\Query->exists(NULL)
#6 /app/vendor/composer/twig/twig/src/Extension/CoreExtension.php(1499): craft\elements\db\ElementQuery->exists()
#7 /app/vendor/composer/craftcms/cms/src/helpers/Template.php(96): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\EntryQuery), 'exists', Array, 'method', false, false)
#8 /app/storage/runtime/compiled_templates/ae/ae1db23960e6cdc2aab1d889e263b119fce3451c280d0c9d3411aa4b6b89beb3.php(95): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\EntryQuery), 'exists', Array, 'method')
#9 /app/vendor/composer/twig/twig/src/Template.php(184): __TwigTemplate_4c8cd642af2b1f864f37dbe0d2b70e92e54355482d6c63f0ebd1f81548de44cf->block_main(Array, Array)
#10 /app/storage/runtime/compiled_templates/77/77b6ca3566966a9642b220d1112d1311093c1ab129cf7273b35829125aef9ab8.php(197): Twig\Template->displayBlock('main', Array, Array)
#11 /app/vendor/composer/twig/twig/src/Template.php(184): __TwigTemplate_8a8e6f9c80b54b44a5afc9bea08ab3b1ddd27f56477f023802e492fdab570081->block_htmlBody(Array, Array)
#12 /app/storage/runtime/compiled_templates/77/77b6ca3566966a9642b220d1112d1311093c1ab129cf7273b35829125aef9ab8.php(96): Twig\Template->displayBlock('htmlBody', Array, Array)
#13 /app/vendor/composer/twig/twig/src/Template.php(407): __TwigTemplate_8a8e6f9c80b54b44a5afc9bea08ab3b1ddd27f56477f023802e492fdab570081->doDisplay(Array, Array)
#14 /app/vendor/composer/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /app/storage/runtime/compiled_templates/ae/ae1db23960e6cdc2aab1d889e263b119fce3451c280d0c9d3411aa4b6b89beb3.php(50): Twig\Template->display(Array, Array)
#16 /app/vendor/composer/twig/twig/src/Template.php(407): __TwigTemplate_4c8cd642af2b1f864f37dbe0d2b70e92e54355482d6c63f0ebd1f81548de44cf->doDisplay(Array, Array)
#17 /app/vendor/composer/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /app/vendor/composer/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#19 /app/vendor/composer/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#20 /app/vendor/composer/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#21 /app/vendor/composer/craftcms/cms/src/web/View.php(397): Twig\Environment->render('_classifieds/en...', Array)
#22 /app/vendor/composer/craftcms/cms/src/web/View.php(458): craft\web\View->renderTemplate('_classifieds/en...', Array)
#23 /app/vendor/composer/craftcms/cms/src/web/Controller.php(235): craft\web\View->renderPageTemplate('_classifieds/en...', Array, 'site')
#24 /app/vendor/composer/craftcms/cms/src/controllers/TemplatesController.php(98): craft\web\Controller->renderTemplate('_classifieds/en...', Array)
#25 [internal function]: craft\controllers\TemplatesController->actionRender('_classifieds/en...', Array)
#26 /app/vendor/composer/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#27 /app/vendor/composer/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#28 /app/vendor/composer/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('render', Array)
#29 /app/vendor/composer/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#30 /app/vendor/composer/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('templates/rende...', Array)
#31 /app/vendor/composer/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#32 /app/vendor/composer/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#33 /app/vendor/composer/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#34 /app/public/index.php(5): yii\base\Application->run()
#35 {main}
Additional Information:
Array
(
    [0] => 42000
    [1] => 1582
    [2] => Incorrect parameter count in the call to native function 'RADIANS'
)
```

Twig:

```
  {% set nearbyEntries = craft.entries
    .section('classifieds')
    .orderBy('distance')
    .id(['not', entry.id])
    .limit(3)
    .mapField({
      location: {
        lat: entry.mapField.lat,
        lng: entry.mapField.lng
      },
      radius: 5000
    })
    .with([
      ['galleryMatrix', {limit: 1}],
      ['galleryMatrix.item:asset']
    ])
  %}
```

This doesn't happen consistently, and seems to be fixed by re-saving the entry.

**Comment by timkelty** [comment]
Easy fix - lat/lng for the `entry.mapField` in question weren't set, so doing a `entry.mapField.isValueEmpty()` check first fixes things.

However, it might not be a bad idea to handle this more gracefully within the plugin itself so it doesn't barf like this w/o the check?
