### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by alexjcollins** [ethercreative/simplemap#258]
### Description:
Updated Craft to 3.4.20 successfully and tried afterwards to upgrade the map plugin which failed.

```
PHP Setting:
max_execution_time = 300
memory_limit = 500M
```
-----------------------------------------------------------

### Invalid Configuration: 
`The table does not exist: {{%maps}}`

### Migration: 
`ether\simplemap\migrations\m190226_143809_craft3_upgrade`

### Output:
```
    > delete from {{%plugins}} ... done (time: 0.001s)
    > Start map data upgrade
    > Upgrade map value Anatomisches Museum der Universität Basel, Pestalozzistrasse 20, Basel, Schweiz
Exception: The table does not exist: {{%maps}} (/home/danieley/public_html/mn/vendor/yiisoft/yii2/db/ActiveRecord.php:438)
#0 /home/danieley/public_html/mn/vendor/yiisoft/yii2/db/ActiveRecord.php(469): yii\db\ActiveRecord::getTableSchema()
#1 /home/danieley/public_html/mn/vendor/yiisoft/yii2/db/BaseActiveRecord.php(500): yii\db\ActiveRecord->attributes()
#2 /home/danieley/public_html/mn/vendor/craftcms/cms/src/db/ActiveRecord.php(38): yii\db\BaseActiveRecord->hasAttribute('ownerId')
#3 /home/danieley/public_html/mn/vendor/ether/simplemap/src/services/MapService.php(113): craft\db\ActiveRecord->__set('ownerId', '4')
#4 /home/danieley/public_html/mn/vendor/ether/simplemap/src/migrations/m190226_143809_craft3_upgrade.php(98): ether\simplemap\services\MapService->saveRecord(Object(ether\simplemap\models\Map), true)
#5 /home/danieley/public_html/mn/vendor/ether/simplemap/src/migrations/m190226_143809_craft3_upgrade.php(48): ether\simplemap\migrations\m190226_143809_craft3_upgrade->_upgrade2()
#6 /home/danieley/public_html/mn/vendor/craftcms/cms/src/db/Migration.php(52): ether\simplemap\migrations\m190226_143809_craft3_upgrade->safeUp()
#7 /home/danieley/public_html/mn/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#8 /home/danieley/public_html/mn/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(ether\simplemap\migrations\m190226_143809_craft3_upgrade))
#9 /home/danieley/public_html/mn/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#10 /home/danieley/public_html/mn/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#11 /home/danieley/public_html/mn/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#12 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#13 /home/danieley/public_html/mn/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /home/danieley/public_html/mn/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /home/danieley/public_html/mn/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#16 /home/danieley/public_html/mn/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#17 /home/danieley/public_html/mn/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#18 /home/danieley/public_html/mn/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#19 /home/danieley/public_html/mn/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#20 /home/danieley/public_html/mn/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /home/danieley/public_html/mn/html/index.php(22): yii\base\Application->run()
#22 {main}
```

### Additional info
Via : @danieleytan

**Comment by jamie-jenks** [comment]
I'm getting the same issue, any update ?
